### ISSUE TITLE
An error caused by the format of the cookies.json file

### ISSUE THREAD

**Issue by eilas** [acheong08/EdgeGPT#125]
My cookie file uses the following form:
```
{
    "MUID": "xxx",
    "MSCC": "xx",
    "zhchatstrongattract": "xxx",
    "ai_session": "xxx"
}
```

The following error occurred while executing EdgeGPT code line 197:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\python\Lib\site-packages\EdgeGPT.py", line 439, in <module>
    asyncio.run(main())
  File "D:\python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\EdgeGPT.py", line 370, in main
    bot = Chatbot()
          ^^^^^^^^^
  File "D:\python\Lib\site-packages\EdgeGPT.py", line 290, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath, self.cookies))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\EdgeGPT.py", line 197, in __init__
    self.session.cookies.set(cookie["name"], cookie["value"])
                             ~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

After I watched the code, I changed the code on line 197 from `self.session.cookies.set(cookie["name"], cookie["value"])` to `self.session.cookies.set(cookie, cookie_file[cookie])` and then it works fine.

**Comment by acheong08** [comment]
Non-standard cookie file not gonna support by default. I'll reference this issue if people as
