### ISSUE TITLE
 An existing connection was forcibly closed by the remote host. 

### ISSUE THREAD

**Issue by Rayquaza-Tim** [acheong08/EdgeGPT#140]
ERROR:
`Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Program Files\Python39\lib\site-packages\httpcore\backends\sync.py", line 62, in start_tls
    raise exc
  File "C:\Program Files\Python39\lib\site-packages\httpcore\backends\sync.py", line 57, in start_tls
    sock = ssl_context.wrap_socket(
  File "C:\Program Files\Python39\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\Python39\lib\ssl.py", line 1041, in _create
    self.do_handshake()
  File "C:\Program Files\Python39\lib\ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Program Files\Python39\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Program Files\Python39\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "C:\Program Files\Python39\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "C:\Program Files\Python39\lib\site-packages\httpcore\_sync\connection.py", line 86, in handle_request
    raise exc
  File "C:\Program Files\Python39\lib\site-packages\httpcore\_sync\connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "C:\Program Files\Python39\lib\site-packages\httpcore\_sync\connection.py", line 150, in _connect
    stream = stream.start_tls(**kwargs)
  File "C:\Program Files\Python39\lib\site-packages\httpcore\backends\sync.py", line 62, in start_tls
    raise exc
  File "C:\Program Files\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Program Files\Python39\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\lib\site-packages\EdgeGPT.py", line 445, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Program Files\Python39\lib\site-packages\EdgeGPT.py", line 376, in main
    bot = Chatbot()
  File "C:\Program Files\Python39\lib\site-packages\EdgeGPT.py", line 296, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath, self.cookies))
  File "C:\Program Files\Python39\lib\site-packages\EdgeGPT.py", line 205, in __init__
    response = self.session.get(
  File "C:\Program Files\Python39\lib\site-packages\httpx\_client.py", line 1045, in get
    return self.request(
  File "C:\Program Files\Python39\lib\site-packages\httpx\_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Program Files\Python39\lib\site-packages\httpx\_client.py", line 908, in send
    response = self._send_handling_auth(
  File "C:\Program Files\Python39\lib\site-packages\httpx\_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Program Files\Python39\lib\site-packages\httpx\_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Program Files\Python39\lib\site-packages\httpx\_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Program Files\Python39\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Program Files\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Program Files\Python39\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。`

I know what happened, but I can't deal with it myself. Thanks for helping.

**Comment by Rayquaza-Tim** [comment]
All right, I have solved this problem by waiting and restarting my laptop.😅 And if someone can  do some exceptional handling, EdgeGPT could be better.
