### ISSUE TITLE
Fatal error on SSL transport . A few days ago it was working fine, yesterday I found this error, the first problem returned to normal, the second problem started with an error

### ISSUE THREAD

**Issue by WWRichard** [acheong08/EdgeGPT#146]
```python
import asyncio
from EdgeGPT import Chatbot, ConversationStyle
bot = Chatbot(cookiePath='cookies.json')
async def main(question):
    global bot
    print(await bot.ask(prompt=question, conversation_style=ConversationStyle.creative))
if __name__ == "__main__":
    qus = ['今天几号', '明天呢']
    for qu in qus:
        asyncio.run(main(qu))
    bot.close()
``` 

```python
{'type':` 2, 'invocationId': '0', 'item': {'messages': [{'text': '今天几号', 'author': 'user', 
'from': {'id': '844428588006103', 'name': None}, 'createdAt': '2023-03-17T01:13:36.4427308+00:00', 
'timestamp': '2023-03-17T01:13:36.439848+00:00', 'locale': 'en-us', 'market': 'en-us', 
'region': 'us', 'messageId': '84869fee-88ce-4b57-b6ea-c0ebee9b6ad9', 
'requestId': '84869fee-d9', 'offense': 'None', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'},
 'contentOrigin': 'cib', 'privacy': None, 'inputMethod': 'Keyboard'}, 
{'text': '你好，这是必应。今天是2023年3月17日，星期五。', 'author': 'bot', 'createdAt': '2023-03-17T01:13:42.3597294+00:00', 'timestamp': '2023-03-17T01:13:42.3597294+00:00', 'messageId': '85163ae8f440a', 
'requestId': '84869fee-88cd9', 'offense': 'None', 'adaptiveCards': [{'type': 'AdaptiveCard', 'version': '1.0', 
'body': [{'type': 'TextBlock', 'text': '你好，这是必应。今天是2023年3月17日，星期五。\n', 'wrap': True}]}], 
'sourceAttributions': [], 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'DeepLeo', 
'privacy': None, 'suggestedResponses': [{'text': '今天的天气怎么样？', 'author': 'user', 'createdAt': '2023-03-17T01:13:47.2559771+00:00', 'timestamp': '2023-03-17T01:13:47.2559771+00:00', 
'messageId': 'f4778bf2-2b6e-4582-b92c-0579fbe4a0b8', 'messageType': 'Suggestion',
 'offense': 'Unknown', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 
'contentOrigin': 'DeepLeo', 'privacy': None}, {'text': '给我讲个笑话。', 'author': 'user', 
'createdAt': '2023-03-17T01:13:47.2559792+00:00', 'timestamp': '2023-03-17T01:13:47.2559792+00:00', 
'messageId': 'e83c491b-33fe-4348-b3da-90ac2bd41802', 'messageType': 'Suggestion', 'offense': 'Unknown',
 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'DeepLeo', 'privacy': None}, 
{'text': '显示最新的国际新闻。', 'author': 'user', 'createdAt': '2023-03-17T01:13:47.2559811+00:00', 
'timestamp': '2023-03-17T01:13:47.2559811+00:00', 'messageId': '07a38fe3-25d0-40', 'messageType': 'Suggestion', 
'offense': 'Unknown', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'DeepLeo', 'privacy': None}], 'spokenText': '今天是2023年3月17日，星期五'}], 'firstNewMessageIndex': 1, 'conversationId': '51D|BingProd|E5FC37976D808DC560A', 'requestId': '84869fee-88ce-4b59', 'conversationExpiryTime': '2023-03-17T07:13:47.3423547Z', 'shouldInitiateConversation': True, 'telemetry': {'metrics': None, 'startTime': '2023-03-17T01:13:36.4399335Z'}, 'throttling': {'maxNumUserMessagesInConversation': 15, 
'numUserMessagesInConversation': 1}, 'result': {'value': 'Success', 'serviceVersion': '20230316.51'}}}
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000022DBAB26050>
transport: <_ProactorSocketTransport fd=700 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 361, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 397, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Traceback (most recent call last):
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 361, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 397, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PY\AndroidADB\EdgeChat.py", line 30, in <module>
    asyncio.run(main(qu))
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\PY\AndroidADB\EdgeChat.py", line 25, in main
    print(await bot.ask(prompt=question, conversation_style=ConversationStyle.creative))
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 327, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 268, in ask_stream
    await self.wss.send_str(append_identifier(self.request.struct))
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_ws.py", line 151, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\http_websocket.py", line 690, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\http_websocket.py", line 646, in _send_frame
    self._write(header + mask + message)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\http_websocket.py", line 664, in _write
    self.transport.write(data)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 392, in write
    self._ssl_protocol._write_appdata(data)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 604, in _write_appdata
    self._process_write_backlog()
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 712, in _process_write_backlog
    self._fatal_error(exc, 'Fatal error on SSL transport')
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 726, in _fatal_error
    self._transport._force_close(exc)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 151, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022DBAB244F0>
```

**Comment by RafaRed** [comment]
Receiving a similar error when I execute "ask" twice in the same instance of Chatbot

**Comment by acheong08** [comment]
aiohttp was terrible. Swapped back to websockets
