### ISSUE TITLE
"Infinity polling exception: 'RuntimeError' object has no attribute 'split'"

### ISSUE THREAD

**Issue by kamil-malinski** [acheong08/EdgeGPT#150]
getting this error when trying to send a second request (the first one always works):

```console
2023-03-17 07:51:50,154 (__init__.py:960 MainThread) ERROR - TeleBot: "Infinity polling exception: 'RuntimeError' object has no attribute 'split'"
2023-03-17 07:51:50,154 (__init__.py:962 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1118, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 91, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 6428, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "/root/BingChatBot/bing.py", line 59, in callback_all
    responseList = asyncio.run(bingChat(callbackQuery.data))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/BingChatBot/bing.py", line 65, in bingChat
    response_dict = await gbot.ask(prompt=messageText, conversation_style=ConversationStyle.creative)
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 329, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 274, in ask_stream
    objects = msg.data.split(DELIMITER)
AttributeError: 'RuntimeError' object has no attribute 'split'
"
```

does anybody know why this is happening?

**Comment by acheong08** [comment]
Something about the API changed. Try again now

**Comment by kamil-malinski** [comment]
the split-error is gone now with 0.6.0, thank you! but now I get this:

```console
callbackQuery: Wie viele Sprachen kannst du sprechen?
2023-03-17 16:07:43,173 (__init__.py:960 MainThread) ERROR - TeleBot: "Infinity polling exception: The future belongs to a different loop than the one specified as the loop argument"
2023-03-17 16:07:43,173 (__init__.py:962 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1118, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 91, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 6428, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "/root/BingChatBot/bing.py", line 59, in callback_all
    responseList = asyncio.run(bingChat(callbackQuery.data))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/BingChatBot/bing.py", line 65, in bingChat
    response_dict = await gbot.ask(prompt=messageText, conversation_style=ConversationStyle.creative)
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 317, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 257, in ask_stream
    await self.wss.close()
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/protocol.py", line 789, in close
    await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 426, in wait_for
    fut = ensure_future(fut, loop=loop)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 615, in ensure_future
    return _ensure_future(coro_or_future, loop=loop)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 621, in _ensure_future
    raise ValueError('The future belongs to a different loop than '
ValueError: The future belongs to a different loop than the one specified as the loop argument
"
2023-03-17 16:07:46,178 (__init__.py:960 MainThread) ERROR - TeleBot: "Infinity polling exception: sent 1000 (OK); then received 1000 (OK)"
2023-03-17 16:07:46,178 (__init__.py:962 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1118, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 91, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 6428, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "/root/BingChatBot/bing.py", line 59, in callback_all
    responseList = asyncio.run(bingChat(callbackQuery.data))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/BingChatBot/bing.py", line 65, in bingChat
    response_dict = await gbot.ask(prompt=messageText, conversation_style=ConversationStyle.creative)
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 317, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 272, in ask_stream
    objects = str(await self.wss.recv()).split(DELIMITER)
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)
"
```

**Comment by acheong08** [comment]
Latest version should fix it
