### ISSUE TITLE
Exception: Authentication failed

### ISSUE THREAD

**Issue by joyspce** [acheong08/EdgeGPT#181]
when I input:   python3 -m EdgeGPT --cookie-file "/mnt/disk/chatGPT/cookies6.json" enter

yestoday it work perfect

but today

get this answer:

//]]></script><script type="text/rms" nonce="S3Dn5Y6zcgnYQ/54K0xV3pDFPhwFpwSAaSRN10jbRNo=">//<![CDATA[
window["fbk_1"] = function() { Feedback.Bootstrap.InitializeFeedback({page:true},"sb_feedback",1,0,0); sj_evt.unbind("fdbkbtstrp_init", window["fbk_1"]); }; sj_evt.bind("fdbkbtstrp_init", window["fbk_1"], 1);;
//]]></script></div><script type="text/javascript" nonce="S3Dn5Y6zcgnYQ/54K0xV3pDFPhwFpwSAaSRN10jbRNo=" >//<![CDATA[
_G.HT=new Date;
//]]></script></body></html>
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/EdgeGPT.py", line 467, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/EdgeGPT.py", line 378, in main
    bot = Chatbot()
  File "/usr/local/lib/python3.8/dist-packages/EdgeGPT.py", line 308, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath, self.cookies))
  File "/usr/local/lib/python3.8/dist-packages/EdgeGPT.py", line 220, in __init__
    raise Exception("Authentication failed")
Exception: Authentication failed

how i can make to work? need help,  thanhs

**Comment by Silhouette6** [comment]
I also met this problem today morning and it also run perfectly in the last few days,what's up with Bing?

**Comment by acheong08** [comment]
Duplicate
- https://github.com/acheong08/EdgeGPT/issues/178
