### ISSUE TITLE
How to fix httpx.ConnectError.

### ISSUE THREAD

**Issue by Sir1usss** [acheong08/EdgeGPT#187]
I had a authenticated account.
I had the cookies exported.
If im in proxy, it occurs 
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chatbot.py", line 11, in <module>
    asyncio.run(main())
  File "D:\anaconda3\envs\EdgeGPT\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\anaconda3\envs\EdgeGPT\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "chatbot.py", line 5, in main
    bot = Chatbot(cookiePath='./cookies.json')
  File "D:\anaconda3\envs\EdgeGPT\lib\site-packages\EdgeGPT.py", line 307, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath, self.cookies))
  File "D:\anaconda3\envs\EdgeGPT\lib\site-packages\EdgeGPT.py", line 212, in __init__
    response = self.session.get(
  File "D:\anaconda3\envs\EdgeGPT\lib\site-packages\httpx\_client.py", line 1045, in get
    return self.request(
  File "D:\anaconda3\envs\EdgeGPT\lib\site-packages\httpx\_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\anaconda3\envs\EdgeGPT\lib\site-packages\httpx\_client.py", line 908, in send
    response = self._send_handling_auth(
  File "D:\anaconda3\envs\EdgeGPT\lib\site-packages\httpx\_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "D:\anaconda3\envs\EdgeGPT\lib\site-packages\httpx\_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "D:\anaconda3\envs\EdgeGPT\lib\site-packages\httpx\_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "D:\anaconda3\envs\EdgeGPT\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\anaconda3\envs\EdgeGPT\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\anaconda3\envs\EdgeGPT\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:1131)
```
If the proxy off, 
```
Exception: Authentication failed
```

thanks a lot

**Comment by Harry-Jing** [comment]
maybe it need to activate http2 support

**Comment by my5123** [comment]
一样的问题，开全局也没用

**Comment by ElieenAndBella** [comment]
how do you solve it
