### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by QiuZiXian** [acheong08/EdgeGPT#2]
I'm in the waiting list of bing chat. Can use this project?
![image](https://user-images.githubusercontent.com/28780269/217981864-f91d4ab8-1943-489e-96d3-335a4727158c.png)

env： win10+python39
I do follow the readme，run developer code crash into bug：

``` EdgeGPT - A demo of reverse engineering the Edge GPT chatbot
        Repo: github.com/acheong08/EdgeGPT
        By: Antonio Cheong

        !help for help

        Type !exit to exit
        Enter twice to send message
    
Initializing...
Traceback (most recent call last):
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Users\dell\anaconda3\envs\python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Users\dell\anaconda3\envs\python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Users\dell\anaconda3\envs\python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\e\project\shida\work\chat-group\chatgpt-test\bing_web\bingai.py", line 43, in <module>
    asyncio.run(main())
  File "D:\Users\dell\anaconda3\envs\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Users\dell\anaconda3\envs\python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "E:\e\project\shida\work\chat-group\chatgpt-test\bing_web\bingai.py", line 10, in main
    await bot.start()
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\EdgeGPT.py", line 210, in start
    self.conversation = Conversation()
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\EdgeGPT.py", line 129, in __init__
    self.struct = response.json()
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 ```

Whether the alternate of bing-chat has no authority

**Comment by acheong08** [comment]
You haven't been accepted into the waitlist

**Comment by QiuZiXian** [comment]
> You haven't been accepted into the waitlist

thanks

**Comment by mikegreen7892003** [comment]
> You haven't been accepted into the waitlist

What is it like to be on the waitlist?

**Comment by acheong08** [comment]
You need to apply at https://bing.com/chat

They will email you if you get in

**Comment by acheong08** [comment]
You can now run without cookies
