### ISSUE TITLE
再上一轮回答未答复之前发起了下一轮的提问，报错ValueError: The future belongs to a different loop than the one specified as the loop argument

### ISSUE THREAD

**Issue by linmp4** [acheong08/EdgeGPT#201]
通过接口调用，再上一轮回答未答复之前，发起了下一轮的提问，报错ValueError: The future belongs to a different loop than the one specified as the loop argument
[ERROR][2023-03-24 20:24:31][wechat_channel.py:163] - The future belongs to a different loop than the one specified as the loop argument
Traceback (most recent call last):
  File "H:\github\bot-on-anything\channel\wechat\wechat_channel.py", line 159, in _do_send
    reply_text = super().build_reply_content(query, context)
  File "H:\github\bot-on-anything\channel\channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "H:\github\bot-on-anything\bridge\bridge.py", line 9, in fetch_reply_content
    return model_factory.create_bot(config.conf().get("model").get("type")).reply(query, context)
  File "H:\github\bot-on-anything\model\bing\new_bing_model.py", line 39, in reply
    answer = asyncio.run(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\EdgeGPT.py", line 328, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\EdgeGPT.py", line 259, in ask_stream
    await self.wss.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\protocol.py", line 789, in close
    await asyncio.wait_for(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 460, in wait_for
    fut = ensure_future(fut, loop=loop)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 671, in ensure_future
    raise ValueError('The future belongs to a different loop than '
ValueError: The future belongs to a different loop than the one specified as the loop argument

**Comment by menachem1** [comment]
Did anyone figure this out?
