### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by PetSven** [acheong08/EdgeGPT#204]
I am using Python 3.11 and EdgeGPT 0.1.12. I created a cookie file like instructed and placed it in the same folder. I checked that I can access Bing chat via the Edge browser.

**Running this code:** 
```
import asyncio
from EdgeGPT import Chatbot, ConversationStyle
async def main():
    bot = Chatbot(cookiePath='./cookies.json')
    print(await bot.ask(prompt="Hello world", conversation_style=ConversationStyle.creative))
    await bot.close()
asyncio.run(main())
```

**Gives me this error message after about 30 seconds:**
```
Traceback (most recent call last):
  File "C:\Users\[user]\OneDrive\Desktop\ChatAI.py", line 11, in <module>
    asyncio.run(main())
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\[user]\OneDrive\Desktop\ChatAI.py", line 8, in main
    print(await bot.ask(prompt="Hello world", conversation_style=ConversationStyle.creative))
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f60a' in position 617: character maps to <undefined>
[Finished in 17.8s]
```

**Comment by PetSven** [comment]
I get a different error message in the latest edgegpt version

**Comment by PetSven** [comment]
Nevermind, I am still getting this error.

**Comment by PetSven** [comment]
I fixed the formatting of my original post and added some more details. My input is the code in my original message.
