### ISSUE TITLE
httpx.TooManyRedirects: Exceeded maximum allowed redirects.

### ISSUE THREAD

**Issue by wzh195879702** [acheong08/EdgeGPT#216]
Traceback (most recent call last):
  File "/root/QChatGPT/plugins/revLibs/main.py", line 105, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/root/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 32, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 111, in get_session
    __sessions__[name] = RevSession(name)
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 41, in __init__
    self.__rev_interface_impl__,_,_ = __rev_interface_impl_class__.create_instance()
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 34, in create_instance
    return EdgeGPTImpl(cookies_dict, revcfg.new_bing_style if hasattr(revcfg, "new_bing_style") else ConversationStyle.balanced), True, cookies_dict
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 38, in __init__
    self.chatbot = Chatbot(cookies=cookies)
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 320, in __init__
    Conversation(self.cookiePath, self.cookies, self.proxy)
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 217, in __init__
    response = self.session.get(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1018, in get
    return self.request(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 785, in request
    return self.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 871, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 907, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 939, in _send_handling_redirects
    raise TooManyRedirects(
httpx.TooManyRedirects: Exceeded maximum allowed redirects.

**Comment by fritx** [comment]
Same here
