### ISSUE TITLE
Exception: No images

### ISSUE THREAD

**Issue by FuseFairy** [acheong08/EdgeGPT#250]
why I always get this error? actually the image is generate success
```
Sending request...
Waiting for results...
.Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\anaconda3\lib\site-packages\ImageGen.py", line 305, in <module>
    image_generator.get_images(args.prompt),
  File "C:\Users\admin\anaconda3\lib\site-packages\ImageGen.py", line 106, in get_images
    raise Exception("No images")
Exception: No images
```

**Comment by tianlichunhong** [comment]
I have the same problem. Don't know the reason.

**Comment by GrandMoff100** [comment]
Same here.
