### ISSUE TITLE
httpx.ReadTimeout: The read operation timed out

### ISSUE THREAD

**Issue by Logzhong** [acheong08/EdgeGPT#253]
My Python version is 3.8.8. I used EdgeGPT before(ver 1.10) but I can't call it in new version. Below is the logs I called it in my VSCode software which should likely response 'You:' but 'httpx.ReadTimeout: The read operation timed out'. 

PS D:\Software\VSCode\script> python -m EdgeGPT --enter-once --style balanced --cookie-file cookie.json

        EdgeGPT - A demo of reverse engineering the Bing GPT chatbot
        Repo: github.com/acheong08/EdgeGPT
        By: Antonio Cheong

        !help for help

        Type !exit to exit

Initializing...
Enter `alt+enter` or `escape+enter` to send a message
Traceback (most recent call last):
  File "D:\Software\Anaconda\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\Software\Anaconda\lib\site-packages\httpcore\backends\sync.py", line 28, in read
    return self._sock.recv(max_bytes)
  File "D:\Software\Anaconda\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "D:\Software\Anaconda\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\Anaconda\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\Software\Anaconda\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\Software\Anaconda\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "D:\Software\Anaconda\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "D:\Software\Anaconda\lib\site-packages\httpcore\_sync\connection.py", line 90, in handle_request
    return self._connection.handle_request(request)
  File "D:\Software\Anaconda\lib\site-packages\httpcore\_sync\http11.py", line 112, in handle_request
    raise exc
  File "D:\Software\Anaconda\lib\site-packages\httpcore\_sync\http11.py", line 91, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "D:\Software\Anaconda\lib\site-packages\httpcore\_sync\http11.py", line 155, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "D:\Software\Anaconda\lib\site-packages\httpcore\_sync\http11.py", line 191, in _receive_event
    data = self._network_stream.read(
  File "D:\Software\Anaconda\lib\site-packages\httpcore\backends\sync.py", line 28, in read
    return self._sock.recv(max_bytes)
  File "D:\Software\Anaconda\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Software\Anaconda\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Software\Anaconda\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Software\Anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Software\Anaconda\lib\site-packages\EdgeGPT.py", line 531, in <module>
    asyncio.run(main())
  File "D:\Software\Anaconda\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Software\Anaconda\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "D:\Software\Anaconda\lib\site-packages\EdgeGPT.py", line 420, in main
    bot = Chatbot(proxy=args.proxy)
  File "D:\Software\Anaconda\lib\site-packages\EdgeGPT.py", line 344, in __init__
    Conversation(self.cookiePath, self.cookies, self.proxy),
  File "D:\Software\Anaconda\lib\site-packages\EdgeGPT.py", line 240, in __init__
    response = self.session.get(
  File "D:\Software\Anaconda\lib\site-packages\httpx\_client.py", line 1045, in get
    return self.request(
  File "D:\Software\Anaconda\lib\site-packages\httpx\_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\Software\Anaconda\lib\site-packages\httpx\_client.py", line 908, in send
    response = self._send_handling_auth(
  File "D:\Software\Anaconda\lib\site-packages\httpx\_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "D:\Software\Anaconda\lib\site-packages\httpx\_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "D:\Software\Anaconda\lib\site-packages\httpx\_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "D:\Software\Anaconda\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\Software\Anaconda\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Software\Anaconda\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

**Comment by Natural12349978** [comment]
I have the same issue.

**Comment by wangyu1997** [comment]
me too

**Comment by yuandj** [comment]
me too, t he same

**Comment by ms8great** [comment]
me too

**Comment by iamumr** [comment]
me too

**Comment by wzy890** [comment]
me too，Have you solved it？

**Comment by wangyu1997** [comment]
话说这个问题没有人有解决方案吗

**Comment by Natural12349978** [comment]
魔法上网应该有用。代理访问应该也有用。但是我不会发自我的手机-------- 原始邮件 --------发件人： Small_yu ***@***.***>日期： 2023年4月3日周一 20:55收件人： acheong08/EdgeGPT ***@***.***>抄送： Natural12349978 ***@***.***>, Comment ***@***.***>主    题： Re: [acheong08/EdgeGPT] httpx.ReadTimeout: The read operation timed out (Issue #253)
话说这个问题没有人有解决方案吗

**Comment by tianlichunhong** [comment]
不是说要升级到Python3.11吗？我之前遇到类似问题，作者说需要升级到Python3.11，确实没有遇到问题了

**Comment by acheong08** [comment]
好像在中国无法使用了。。。必须用VPN。

**Comment by acheong08** [comment]
I'll try to fix

**Comment by Natural12349978** [comment]
> I'll try to fix

Thanks。感谢你为此做出的努力！

**Comment by acheong08** [comment]
Report:
- 1.1.1.1 is blocked.
- They now check if wss x-forwarded-for is the same as the one for `/edgesvc/turing/conversation/create`
- Conversations must remain on the same IP.

At least that is what I assume.

**Comment by Natural12349978** [comment]
> 不是说要升级到Python3.11吗？我之前遇到类似问题，作者说需要升级到Python3.11，确实没有遇到问题了

我termux里就是python3.11。无魔法不能用。开代理不清楚。没试。你现在无魔法能用嘛？

**Comment by Natural12349978** [comment]
> Report:
> 
> * 1.1.1.1 is blocked.
> * They now check if wss x-forwarded-for is the same as the one for `/edgesvc/turing/conversation/create`
> * Conversations must remain on the same IP.
> 
> At least that is what I assume.

也就是说现在要开两个代理。一个创建对话，一个持续对话？
（That means we need to open two proxys now. Create a conversation, continue a conversation?）

**Comment by acheong08** [comment]
不用。`x-forward-for` 骗得过他.

**Comment by JimouChen** [comment]
之前出现这个问题，我是这样解决的，可以尝试换一个代理，然后重新保存cookies.json，这样就不会报错了。
(This problem occurred before, and I solved it in this way. You can try to change a proxy, and then save a new cookies.json, so that no error will be reported.)
