### ISSUE TITLE
KeyError: 'conversationSignature'

### ISSUE THREAD

**Issue by Patrizio-programs** [acheong08/EdgeGPT#261]
I'm having this error all of a sudden. I actually integrated the code to work in a Telegram bot. I suspect there is an issue in the Conversation class but I couldnt figure it out. I'll keep checking.

Traceback (most recent call last):
  File "main.py", line 47, in <module>
    chatbot = Chatbot(cookiePath='./cookies.json')
  File "/home/runner/EdgeGPT/EdgeGPT.py", line 346, in __init__
    self.chat_hub: ChatHub = ChatHub(
  File "/home/runner/EdgeGPT/EdgeGPT.py", line 276, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
KeyError: 'conversationSignature'

Update:

So it seems I get the same issue trying to run it in my terminal.

Traceback (most recent call last):
  File "C:\Users\patri\OneDrive\Desktop\DEV\JamaicanAI\EdgeGPT\src\EdgeGPT.py", line 501, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\patri\OneDrive\Desktop\DEV\JamaicanAI\EdgeGPT\src\EdgeGPT.py", line 400, in main
    bot = Chatbot(proxy=args.proxy)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\OneDrive\Desktop\DEV\JamaicanAI\EdgeGPT\src\EdgeGPT.py", line 324, in __init__
    self.chat_hub: ChatHub = ChatHub(
                             ^^^^^^^^
  File "C:\Users\patri\OneDrive\Desktop\DEV\JamaicanAI\EdgeGPT\src\EdgeGPT.py", line 251, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'conversationSignature'


Update: I figured it's an issue with the cookies.
I printed the conversation.struct.
{'result': {'value': 'Forbidden', 'message': 'Sorry, you are not allowed to access this service.'}}

**Comment by laojianzi** [comment]
I also encountered it, everything returned to normal when I made sure that all *.bing.com went to the US node
