### ISSUE TITLE
connectionError

### ISSUE THREAD

**Issue by Yaaasuo** [acheong08/EdgeGPT#264]
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpcore\backends\sync.py", line 62, in start_tls
    raise exc
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpcore\backends\sync.py", line 57, in start_tls
    sock = ssl_context.wrap_socket(
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpcore\_sync\http_proxy.py", line 261, in handle_request
    connect_response = self._connection.handle_request(
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpcore\_sync\connection.py", line 86, in handle_request
    raise exc
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpcore\_sync\connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpcore\_sync\connection.py", line 150, in _connect
    stream = stream.start_tls(**kwargs)
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpcore\backends\sync.py", line 62, in start_tls
    raise exc
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:/ZXF/crawler/title.py", line 14, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "E:/ZXF/crawler/title.py", line 8, in main
    bot = Chatbot(cookiePath= path)
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\EdgeGPT.py", line 307, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath, self.cookies))
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\EdgeGPT.py", line 212, in __init__
    response = self.session.get(
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpx\_client.py", line 1045, in get
    return self.request(
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpx\_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpx\_client.py", line 908, in send
    response = self._send_handling_auth(
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpx\_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpx\_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpx\_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Administrator\anaconda3\envs\edgegpt\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:1131)

**Comment by tandaly** [comment]
close vpn proxy
