### ISSUE TITLE
how to solve this issue

### ISSUE THREAD

**Issue by Yaaasuo** [acheong08/EdgeGPT#281]
10
9
8
7
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\lib\site-packages\websockets\legacy\client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "C:\Users\Administrator\anaconda3\lib\asyncio\base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\Administrator\anaconda3\lib\asyncio\base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\Administrator\anaconda3\lib\asyncio\proactor_events.py", line 703, in sock_connect
    return await self._proactor.connect(sock, address)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\lib\asyncio\tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ZXF\crawler\title.py", line 43, in <module>
    asyncio.run(main(rounds = 10, title = title))
  File "C:\Users\Administrator\anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "E:\ZXF\crawler\title.py", line 27, in main
    response = await bot.ask(prompt=input)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\EdgeGPT.py", line 317, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "C:\Users\Administrator\anaconda3\lib\site-packages\EdgeGPT.py", line 259, in ask_stream
    self.wss = await websockets.connect(
  File "C:\Users\Administrator\anaconda3\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "C:\Users\Administrator\anaconda3\lib\asyncio\tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

进程已结束,退出代码1

**Comment by 50-Course** [comment]
Hi,

Could you provide steps to reproduce your error? It would help me help you faster.

**Comment by VMTask** [comment]
Check your proxy server.

**Comment by Yaaasuo** [comment]
import asyncio
from EdgeGPT import Chatbot, ConversationStyle
import os
import time
import pandas as pd
import json
os.environ["HTTP_PROXY"] = "http://127.0.0.1:7890"
os.environ["HTTPS_PROXY"] = "http://127.0.0.1:7890"

path = r"E:\ZXF\crawler\stacey_cookies.json"



async def main(rounds = 5, title = None):
    global path

    r = rounds
    description = "给上述几个标题情感打分，取分范围0-100，分数越高表示情感越正向，并且将结果按照csv的格式返回，第一列为原标题，第二列为得分"
    while rounds:
        print(rounds)
        bot = Chatbot(cookiePath=path)
        with open("{}.txt".format(r - rounds), mode="w", encoding="utf-8") as fp:
            sample = title[10 * (r - rounds):10 * (r - rounds + 1)]
            sample.append(description)
            input = "\n".join(sample)
            try:
                response = await bot.ask(prompt=input)
            except TimeoutError as e:
                time.sleep(5)
                response = await bot.ask(prompt=input, conversation_style=ConversationStyle.creative, wss_link="wss://sydney.bing.com/sydney/ChatHub")
            fp.write(response["item"]["messages"][1]["text"])
        rounds -= 1
        await asyncio.sleep(3)
        await bot.close()

if __name__ == "__main__":
    # text path:
    start = time.time()
    batch = 10
    rounds = 5
    df = pd.read_csv("002459.csv")
    title = df["title"].tolist()
    asyncio.run(main(rounds = 10, title = title))
    # print(response["item"]["messages"][1]["text"])
    end = time.time()
    print((end - start))
this is my code

**Comment by Yaaasuo** [comment]
I have a question: can I visit new bing by this project without visiting this site("wss://sydney.bing.com/sydney/ChatHub"); there may be two ways: 1. use a VPN server; 2. directly visit the new bing site(in fact we can obtain the access to new bing's websit).

**Comment by VMTask** [comment]
No,bing's site also use this.
