### ISSUE TITLE
How should I handle this error？

### ISSUE THREAD

**Issue by xiejavadechengyunsheng** [acheong08/EdgeGPT#284]
pydev debugger: Unable to find real location for: <frozen genericpath>
Initializing...
Enter `alt+enter` or `escape+enter` to send a message
Traceback (most recent call last):
  File "D:\soft\Python310\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\soft\Python310\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\soft\Python310\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:/code/EdgeGPT-master/EdgeGPT-new/src/EdgeGPT.py", line 418, in main
    bot = Chatbot(proxy=args.proxy)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:/code/EdgeGPT-master/EdgeGPT-new/src/EdgeGPT.py", line 342, in __init__
    Conversation(self.cookiePath, self.cookies, self.proxy),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:/code/EdgeGPT-master/EdgeGPT-new/src/EdgeGPT.py", line 255, in __init__
    raise NotAllowedToAccess(self.struct["result"]["message"])
NotAllowedToAccess: Sorry, you need to login first to access this service.

Process finished with exit code 1

**Comment by xiejavadechengyunsheng** [comment]
这个错误是否是因为没有挂梯子
