### ISSUE TITLE
 raise Exception("Authentication failed") Exception: Authentication failed

### ISSUE THREAD

**Issue by peixikk** [acheong08/EdgeGPT#31]
Initializing...
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\pcesi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\EdgeGPT.py", line 333, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\pcesi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\EdgeGPT.py", line 278, in main
    bot = Chatbot()
  File "C:\Users\pcesi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\EdgeGPT.py", line 218, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation())
  File "C:\Users\pcesi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\EdgeGPT.py", line 111, in __init__
    raise Exception("Authentication failed")
Exception: Authentication failed

**Comment by coolmian** [comment]
same here

**Comment by Manamama** [comment]
See [main thread](https://github.com/acheong08/EdgeGPT/issues/28) (plus my NLP test jokes there).

**Comment by QiuZiXian** [comment]
same here

**Comment by 123seven** [comment]
same here

**Comment by RLBOT1v1Replayproprogrammer** [comment]
same

**Comment by bifrostx** [comment]
same here

**Comment by omar2205** [comment]
Hi, don't send "same here", just upvote the issue. You're sending people notifications for no positive reason.

**Comment by cx9208** [comment]
i seems got banned by bing, use website chat also show "something wrong...."

**Comment by acheong08** [comment]
> i seems got banned by bing, use website chat also show "something wrong...."

What version of this repo were you using?

**Comment by acheong08** [comment]
If you were using anything before 0.0.40 and sent an abnormal number of requests, you will get banned

**Comment by cx9208** [comment]
> If you were using anything before 0.0.40 and sent an abnormal number of requests, you will get banned


yes, version 0.0.3, lol

**Comment by acheong08** [comment]
> > If you were using anything before 0.0.40 and sent an abnormal number of requests, you will get banned
> 
> yes, version 0.0.3, lol

☠️

**Comment by acheong08** [comment]
With any reverse engineering library, you must always stay up to date as the companies try to stop us
