### ISSUE TITLE
OSError: [WinError 64] 指定的网络名不再可用。

### ISSUE THREAD

**Issue by Harry-Jing** [acheong08/EdgeGPT#34]
```
C:\Users\Harry>python -m EdgeGPT --bing-cookie <cookies>

        EdgeGPT - A demo of reverse engineering the Bing GPT chatbot
        Repo: github.com/acheong08/EdgeGPT
        By: Antonio Cheong

        !help for help

        Type !exit to exit
        Enter twice to send message

Initializing...

You:
你好

Bot:
Traceback (most recent call last):
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 489, in finish_recv
    return ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 333, in <module>
    asyncio.run(main())
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 304, in main
    async for final, response in bot.ask_stream(prompt=prompt):
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 232, in ask_stream
    async for response in self.chat_hub.ask_stream(prompt=prompt):
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 178, in ask_stream
    self.wss = await websockets.connect("wss://sydney.bing.com/sydney/ChatHub")
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1097, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1127, in _create_connection_transport
    await waiter
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 286, in _loop_reading
    length = fut.result()
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 821, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 493, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] 指定的网络名不再可用。
```

**Comment by acheong08** [comment]
?

**Comment by Harry-Jing** [comment]
When I close the proxy. It will run normaly

**Comment by Harry-Jing** [comment]
After my several test this condition will hanppen randomly

**Comment by Harry-Jing** [comment]
```
PS C:\Users\Harry> & C:/Users/Harry/AppData/Local/Programs/Python/Python310/python.exe c:/Users/Harry/Desktop/test.py
Traceback (most recent call last):
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 489, in finish_recv
    return ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Harry\Desktop\test.py", line 11, in <module>
    asyncio.run(main())
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "c:\Users\Harry\Desktop\test.py", line 6, in main
    print(await bot.ask(prompt="你可以做些什么"))
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 224, in ask
    async for final, response in self.chat_hub.ask_stream(prompt=prompt):
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 178, in ask_stream
    self.wss = await websockets.connect("wss://sydney.bing.com/sydney/ChatHub")
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1097, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1127, in _create_connection_transport
    await waiter
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 286, in _loop_reading
    length = fut.result()
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 821, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Harry\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 493, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] 指定的网络名不再可用。
```

**Comment by Harry-Jing** [comment]
I have no idea about this

**Comment by acheong08** [comment]
Something wrong with your proxy

**Comment by sfz009900** [comment]
@acheong08 
Here's something somewhat similar to the edgegpt model www.chatwithbing.com

**Comment by myfingerhurt** [comment]
It's better not to automatically switch between exit nodes based on their latency.

**Comment by Harry-Jing** [comment]
It works pretty fine now

**Comment by WilsonZrB** [comment]
@Harry-Jing Same problem occurs to me, how did you fix it
