### ISSUE TITLE
error wen i run the python file

### ISSUE THREAD

**Issue by python-tip** [acheong08/EdgeGPT#372]
the comman i run python3 EdgeGPT.py --cookie-file=cookies.json

the error i got
Traceback (most recent call last):
  File "/home/ubuntu/EdgeGPT/src/EdgeGPT.py", line 871, in <module>
    main()
  File "/home/ubuntu/EdgeGPT/src/EdgeGPT.py", line 867, in main
    asyncio.run(async_main(args))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/EdgeGPT/src/EdgeGPT.py", line 793, in async_main
    async for final, response in bot.ask_stream(
  File "/home/ubuntu/EdgeGPT/src/EdgeGPT.py", line 662, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "/home/ubuntu/EdgeGPT/src/EdgeGPT.py", line 430, in ask_stream
    self.wss = await websockets.connect(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1107, in _create_connection_transport
    protocol = protocol_factory()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/client.py", line 69, in __init__
    super().__init__(**kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/protocol.py", line 235, in __init__
    self._drain_lock = asyncio.Lock(
  File "/usr/lib/python3.10/asyncio/locks.py", line 78, in __init__
    super().__init__(loop=loop)
  File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary

**Comment by VMTask** [comment]
```bash
pip install websockets --upgrade
```
