### ISSUE TITLE
response error

### ISSUE THREAD

**Issue by cetari** [acheong08/EdgeGPT#374]
response["item"]["messages"][-1]["contentOrigin"] == "Apology"

**Comment by xming521** [comment]
同

**Comment by Tudor44** [comment]
Hello @cetari 

this issue occurred when is reached the call limit within 24 hours.

@acheong08 I would propose of adding a more readable message on trigger of this error.

**Comment by acheong08** [comment]
Can you explain the issue and provide a full trace log?

**Comment by Tudor44** [comment]
> Can you explain the issue and provide a full trace log?

This is mine during the bot.ask() call:

`Traceback (most recent call last):
  File "/Users/gaetano.dorsi/Desktop/amanuensis-simple-ai-agent/env/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/Users/gaetano.dorsi/Desktop/amanuensis-simple-ai-agent/src/main.py", line 33, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/gaetano.dorsi/Desktop/amanuensis-simple-ai-agent/src/main.py", line 26, in main
    await (asyncio.gather(firstWorker()))
  File "/Users/gaetano.dorsi/Desktop/amanuensis-simple-ai-agent/src/main.py", line 16, in firstWorker
    result = await bot.ask(prompt="Hello world", conversation_style=ConversationStyle.creative, wss_link="wss://sydney.bing.com/sydney/ChatHub")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gaetano.dorsi/Desktop/amanuensis-simple-ai-agent/env/lib/python3.11/site-packages/EdgeGPT.py", line 653, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/Users/gaetano.dorsi/Desktop/amanuensis-simple-ai-agent/env/lib/python3.11/site-packages/EdgeGPT.py", line 566, in ask_stream
    response["item"]["messages"][-1]["contentOrigin"] == "Apology"
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'messages'`

**Comment by InterestingDarkness** [comment]
https://github.com/acheong08/EdgeGPT/pull/404
adds a detection of Throttled or CAPTCHA

**Comment by PFython** [comment]
> Hello @cetari
> 
> this issue occurred when is reached the call limit within 24 hours.
> 
> @acheong08 I would propose of adding a more readable message on trigger of this error.

Confirmed.  My recent Pull Request https://github.com/acheong08/EdgeGPT/pull/396 actually uses the current error to know when the daily limit (currently 200) has been reached, and cycle through other cookies.json files if they're available to carry on working.
