### ISSUE TITLE
[Bug]: TypeError: unhashable type: 'bytearray' when use socks5 proxy

### ISSUE THREAD

**Issue by laulguo** [acheong08/EdgeGPT#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

TypeError: unhashable type: 'bytearray' when use socks5 proxy

### Steps to reproduce the problem

use python -m EdgeGPT --proxy socks5://127.0.0.1:1080 --cookie-file cookie_bing.json

### What should have happened?

TypeError: unhashable type: 'bytearray'

### Version where the problem happens

Name: EdgeGPT
Version: 0.3.5
Summary: Reverse engineered Edge Chat API
Home-page: https://github.com/acheong08/EdgeGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: d:\researching\python310\lib\site-packages
Requires: BingImageCreator, certifi, httpx, prompt-toolkit, requests, rich, websockets
Required-by:

### What Python version are you running this with?

Python 3.10.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Traceback (most recent call last):
  File "D:\Researching\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Researching\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Researching\Python310\lib\site-packages\EdgeGPT.py", line 870, in <module>
    main()
  File "D:\Researching\Python310\lib\site-packages\EdgeGPT.py", line 866, in main
    asyncio.run(async_main(args))
  File "D:\Researching\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Researching\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\Researching\Python310\lib\site-packages\EdgeGPT.py", line 731, in async_main
    bot = await Chatbot.create(proxy=args.proxy, cookies=args.cookies)
  File "D:\Researching\Python310\lib\site-packages\EdgeGPT.py", line 618, in create
    await _Conversation.create(self.cookies, self.proxy),
  File "D:\Researching\Python310\lib\site-packages\EdgeGPT.py", line 372, in create
    response = await client.get(
  File "D:\Researching\Python310\lib\site-packages\httpx\_client.py", line 1754, in get
    return await self.request(
  File "D:\Researching\Python310\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\Researching\Python310\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "D:\Researching\Python310\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\Researching\Python310\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\Researching\Python310\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\Researching\Python310\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\Researching\Python310\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\Researching\Python310\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\Researching\Python310\lib\site-packages\httpcore\_async\socks_proxy.py", line 292, in handle_async_request
    raise exc
  File "D:\Researching\Python310\lib\site-packages\httpcore\_async\socks_proxy.py", line 240, in handle_async_request
    await _init_socks5_connection(**kwargs)
  File "D:\Researching\Python310\lib\site-packages\httpcore\_async\socks_proxy.py", line 93, in _init_socks5_connection
    response = conn.receive_data(incoming_bytes)
  File "D:\Researching\Python310\lib\site-packages\socksio\socks5.py", line 382, in receive_data
    reply = SOCKS5Reply.loads(data)
  File "D:\Researching\Python310\lib\site-packages\socksio\socks5.py", line 262, in loads
    addr=decode_address(AddressType.from_socks5_atype(atype), data[4:-2]),
TypeError: unhashable type: 'bytearray'
```

**Comment by Glucy-2** [comment]
Same problem
