### ISSUE TITLE
New update json.decoder.JSONDecodeError 

### ISSUE THREAD

**Issue by leolrg** [acheong08/EdgeGPT#4]
```
raceback (most recent call last):
  File "/Users/leolrg/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leolrg/Downloads/EdgeGPT/src/EdgeGPT.py", line 135, in __init__
    self.struct = response.json()
  File "/Users/leolrg/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leolrg/Downloads/EdgeGPT/src/EdgeGPT.py", line 293, in <module>
    asyncio.run(main())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/leolrg/Downloads/EdgeGPT/src/EdgeGPT.py", line 254, in main
    bot = Chatbot()
  File "/Users/leolrg/Downloads/EdgeGPT/src/EdgeGPT.py", line 203, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation())
  File "/Users/leolrg/Downloads/EdgeGPT/src/EdgeGPT.py", line 137, in __init__
    raise Exception(
TypeError: __init__() missing 3 required positional arguments: 'msg', 'doc', and 'pos'
```

**Comment by PetterZhukov** [comment]
I also met this problem

**Comment by PetterZhukov** [comment]
> ```
> raceback (most recent call last):
>   File "/Users/leolrg/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 971, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/leolrg/Downloads/EdgeGPT/src/EdgeGPT.py", line 135, in __init__
>     self.struct = response.json()
>   File "/Users/leolrg/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 975, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/leolrg/Downloads/EdgeGPT/src/EdgeGPT.py", line 293, in <module>
>     asyncio.run(main())
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/Users/leolrg/Downloads/EdgeGPT/src/EdgeGPT.py", line 254, in main
>     bot = Chatbot()
>   File "/Users/leolrg/Downloads/EdgeGPT/src/EdgeGPT.py", line 203, in __init__
>     self.chat_hub: ChatHub = ChatHub(Conversation())
>   File "/Users/leolrg/Downloads/EdgeGPT/src/EdgeGPT.py", line 137, in __init__
>     raise Exception(
> TypeError: __init__() missing 3 required positional arguments: 'msg', 'doc', and 'pos'
> ```

https://github.com/acheong08/EdgeGPT/issues/2 let‘s see this issue,it solve the same problem

**Comment by GreatestOfAllTimee** [comment]
same here.

run `python -m EdgeGPT "MY_COOKIES"` and get same as error above.

**Comment by leolrg** [comment]
>let‘s see this issue,it solve the same problem

No that one is the version before where you need your own Cookies.

**Comment by leolrg** [comment]
>run python -m EdgeGPT "MY_COOKIES" and get same as error above.

You ran into the same problem even with your own cookies that has beta access?

**Comment by GreatestOfAllTimee** [comment]
really? here are the error output:

- Python Version: `Python 3.10.8`

<details>

```
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 135, in __init__
    self.struct = response.json()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 293, in <module>
    asyncio.run(main())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 254, in main
    bot = Chatbot()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 203, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 137, in __init__
    raise Exception(
TypeError: JSONDecodeError.__init__() missing 3 required positional arguments: 'msg', 'doc', and 'pos'
```

</details>

---

> You ran into the same problem even with your own cookies that has beta access?

I just joined the waitlist but didn't get access yet. but it seems like run without cookies argument throw a similar error:

`python -m EdgeGPT` Output:

<details>

```
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 135, in __init__
    self.struct = response.json()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 293, in <module>
    asyncio.run(main())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 254, in main
    bot = Chatbot()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 203, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 137, in __init__
    raise Exception(
TypeError: JSONDecodeError.__init__() missing 3 required positional arguments: 'msg', 'doc', and 'pos'
```

</details

**Comment by PetterZhukov** [comment]
> 

it may be solved if you  get access ,I guess; I have joined the waitlist,too. And I met the same problem

**Comment by leolrg** [comment]
> it may be solved if you get access ,I guess; I have joined the waitlist,too. And I met the same problem

The new version is supposed to use someone else's shared account that has the beta access so we do not need to use our own cookies.

**Comment by PetterZhukov** [comment]
> > it may be solved if you get access ,I guess; I have joined the waitlist,too. And I met the same problem
> 
> The new version is supposed to use someone else's shared account that has the beta access so we do not need to use our own cookies.

oh I know,is 'python -m EdgeGPT' ?I try it and met the same error ,too. Yes, there may be other reasons

**Comment by acheong08** [comment]
Hello. The reason is because it didn't update properly

**Comment by acheong08** [comment]
You have to completely uninstall it and reinstall

`pip3 uninstall EdgeGPT`

`pip3 install EdgeGPT`

**Comment by acheong08** [comment]
Python caches are weird

**Comment by acheong08** [comment]
> run python -m EdgeGPT "MY_COOKIES" and get same as error above.

This means your cookies aren't valid. Just run it as `python3 -m EdgeGPT` without any other agruments

**Comment by leolrg** [comment]
> You have to completely uninstall it and reinstall
> pip3 uninstall EdgeGPT
> pip3 install EdgeGPT

Didn't work. I even downloaded the repository and use it instead of the pip version but got the same error.

**Comment by acheong08** [comment]
> Didn't work. I even downloaded the repository and use it instead of the pip version but got the same error.

`git clone https://github.com/acheong08/EdgeGPT`
`cd EdgeGPT`
`pip3 install .`

Is that how you did it?

**Comment by leolrg** [comment]
>Is that how you did it?

I 
> cd EdgeGPT/src
> python3 EdgeGPT.py

**Comment by acheong08** [comment]
Yeah, don't do that. Just `pip3 install .` inside the directory and `python3 -m EdgeGPT`

If you have it cloned, remember to `git pull`

**Comment by acheong08** [comment]
I update very frequently so always update to the latest version

**Comment by PetterZhukov** [comment]
> python3 -m EdgeGPT

I re-pip the moduel ,but I still met this error, that's so bad

**Comment by Jimmy-Z** [comment]
I did a little debug, and I think I've found the bug: just remove `br` from `accept-encoding` header.

explanation:
* AFAICT requests doesn't handle brotli
* bing doesn't actually use brotli so it's fine if you're using your own cookie
* but the shared service will

**Comment by leolrg** [comment]
> I did a little debug, and I think I've found the bug: just remove br from accept-encoding header.

Thanks! it worked!

**Comment by zjrwtx** [comment]
> I did a little debug, and I think I've found the bug: just remove `br` from `accept-encoding` header.
> 
> explanation:
> 
> * AFAICT requests doesn't handle brotli
> * bing doesn't actually use brotli so it's fine if you're using your own cookie
> * but the shared service will

![image](https://user-images.githubusercontent.com/86822589/218032294-e50144a6-d678-4188-b983-130e739a5f94.png)
i have tried it  ,but it still not works,is it my error?

**Comment by Jimmy-Z** [comment]
Are you using your own cookie? are you still on the waitlist?

**Comment by zjrwtx** [comment]
> Are you using your own cookie? are you still on the waitlist?

i use the public server,Without a cookie

**Comment by KyleZhang0536** [comment]
> 

Works for me

**Comment by Jimmy-Z** [comment]
> > Are you using your own cookie? are you still on the waitlist?
> 
> i use the public server,Without a cookie

Try my fork (or wait for my pr to be merged), should have a more informational exception output
https://github.com/Jimmy-Z/EdgeGPT

**Comment by zjrwtx** [comment]
> > > Are you using your own cookie? are you still on the waitlist?
> > 
> > 
> > i use the public server,Without a cookie
> 
> Try my fork (or wait for my pr to be merged), should have a more informational exception output https://github.com/Jimmy-Z/EdgeGPT

thanks，it works

**Comment by acheong08** [comment]
> > I did a little debug, and I think I've found the bug: just remove `br` from `accept-encoding` header.
> 
> Works for me

That's interesting. Might be a difference in our request versions. I'm fixing now

**Comment by acheong08** [comment]
- https://github.com/acheong08/EdgeGPT/releases/tag/0.0.11
