### ISSUE TITLE
[Bug]: CaptchaChallenge: User needs to solve CAPTCHA to continue.

### ISSUE THREAD

**Issue by developerfromjokela** [acheong08/EdgeGPT#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Trying to use GPT, I get an error message: CaptchaChallenge: User needs to solve CAPTCHA to continue.

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

Script should've ran 

### Version where the problem happens

0.4.4

### What Python version are you running this with?

3.9

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
none
```

### Console logs

```Shell
CaptchaChallenge: User needs to solve CAPTCHA to continue.
```

**Comment by developerfromjokela** [comment]
Hmm, seems to work on latest 0.5.0 version

**Comment by acheong08** [comment]
Might be a cookie thing

**Comment by scmanjarrez** [comment]
This error happens when you haven't chatted with Bing Chat once (or at least my users reported that). So chat at least one time with Bing Chat and then export your cookies.

**Comment by developerfromjokela** [comment]
> 

all accounts had chatted before exporting cookies, strangely enough error came when rumored API changes happened. Issue seemed to go away after I upgraded to new version, which doesn't use cookies anymore.

**Comment by acheong08** [comment]
> Hmm, seems to work on latest 0.5.0 version

Closing then...

**Comment by vaibhavard** [comment]
> Same issue here.... 

*Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.*
------------------------------------------------------------------
I have deployed my app on streamlit and it was previously (till now) working great!
**Though recently i saw this Error on the app.... I executed the same code on my local pc and the error was no longer showing up... The error shows up (most probably) when you login from a different ip /location.**
How do i deal with this? 
Thanks 😀



FULL BACKTRACE:
-------------------------------------------------------------------
`INFO:httpx:HTTP Request: GET https://edgeservices.bing.com/edgesvc/turing/conversation/create "HTTP/1.1 200 OK"

2023-06-08 13:24:15.607 Uncaught app exception

Traceback (most recent call last):

  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script

    exec(code, module.__dict__)

  File "/app/inta2/aa.py", line 931, in <module>

    data2 = chat2(title,modded)

  File "/app/inta2/aa.py", line 529, in chat2

    asyncio.run(run_main_with_timeout())

  File "/home/appuser/venv/lib/python3.9/site-packages/nest_asyncio.py", line 35, in run

    return loop.run_until_complete(task)

  File "/home/appuser/venv/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete

    return f.result()

  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result

    raise self._exception

  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step

    result = coro.send(None)

  File "/app/inta2/aa.py", line 524, in run_main_with_timeout

    await asyncio.wait_for(main(), timeout=6000)

  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for

    return fut.result()

  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result

    raise self._exception

  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step

    result = coro.send(None)

  File "/app/inta2/aa.py", line 506, in main

    async for final, response in bot.ask_stream(prompt=name,conversation_style=modded,wss_link="wss://sydney.bing.com/sydney/ChatHub"):

  File "/home/appuser/venv/lib/python3.9/site-packages/EdgeGPT/EdgeGPT.py", line 132, in ask_stream

    async for response in self.chat_hub.ask_stream(

  File "/home/appuser/venv/lib/python3.9/site-packages/EdgeGPT/chathub.py", line 170, in ask_stream

    raise Exception(

Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.`

**Comment by acheong08** [comment]
IP based. Can't fix
