### ISSUE TITLE
[Bug]: History for Chinese support.

### ISSUE THREAD

**Issue by VMTask** [acheong08/EdgeGPT#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I'm trying to ask bing some questions,and I use the history-file options.
When bing's answer is done,it show me this error:
```
Traceback (most recent call last):
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Scripts\edge-gpt-script.py", line 33, in <module>
    sys.exit(load_entry_point('EdgeGPT==0.6.7', 'console_scripts', 'edge-gpt')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py", line 908, in main
    asyncio.run(async_main(args))
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py", line 826, in async_main
    p_hist(response[wrote:], end="")
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py", line 745, in logger
    print(*args, **kwargs, flush=True)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f60a' in position 0: illegal multibyte sequence
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002AA05059090>
Exception ignored in: <function ClientResponse.__del__ at 0x000002AA01C03600>
Traceback (most recent call last):
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 811, in __del__
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 178, in release
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 663, in _release
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_proto.py", line 63, in close
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\sslproto.py", line 111, in close
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\sslproto.py", line 622, in _start_shutdown
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 724, in call_later
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 737, in call_at
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 519, in _check_closed
RuntimeError: Event loop is closed
```

### Steps to reproduce the problem

1.Run `python3 -m EdgeGPT --history-file his.json`
2.Ask Chinese questions.

### What should have happened?

It will write the output to the history file.

### Version where the problem happens

Name: EdgeGPT
Version: 0.6.7
Summary: Reverse engineered Edge Chat API
Home-page: https://github.com/acheong08/EdgeGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: BingImageCreator, certifi, httpx, prompt_toolkit, requests, rich, websockets
Required-by:

### What Python version are you running this with?

Python 3.11.0

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
python3 -m EdgeGPT --history-file his.json
```

### Console logs

```Shell
EdgeGPT - A demo of reverse engineering the Bing GPT chatbot
        Repo: github.com/acheong08/EdgeGPT
        By: Antonio Cheong

        !help for help

        Type !exit to exit

Initializing...
Enter `alt+enter` or `escape+enter` to send a message

You:
我刚刚说了什么？

Bot:
你刚刚问我你刚刚说了什么。
Traceback (most recent call last):
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Scripts\edge-gpt-script.py", line 33, in <module>
    sys.exit(load_entry_point('EdgeGPT==0.6.7', 'console_scripts', 'edge-gpt')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py", line 908, in main
    asyncio.run(async_main(args))
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py", line 826, in async_main
    p_hist(response[wrote:], end="")
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py", line 745, in logger
    print(*args, **kwargs, flush=True)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f60a' in position 0: illegal multibyte sequence
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002AA05059090>
Exception ignored in: <function ClientResponse.__del__ at 0x000002AA01C03600>
Traceback (most recent call last):
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 811, in __del__
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 178, in release
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 663, in _release
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_proto.py", line 63, in close
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\sslproto.py", line 111, in close
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\sslproto.py", line 622, in _start_shutdown
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 724, in call_later
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 737, in call_at
  File "C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 519, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by VMTask** [comment]
#446
