### ISSUE TITLE
[Bug]: Authentication failed

### ISSUE THREAD

**Issue by Zapzatron** [acheong08/EdgeGPT#455]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

```python
None:  01001000 01100101 01101100 01110000 00101100 0010000001001001 00100111 01101101 0010000001100001 00100000 01101000 01101111 01110011 01110100 01100001 01100111 01100101 00101110
Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 60, in <module>
    bot_response = asyncio.run(bing_chat(prompt=text))
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 48, in bing_chat
    gbot = await Chatbot().create()
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 621, in __init__
    _Conversation(self.proxy, cookies=cookies),
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 343, in __init__
    raise Exception("Authentication failed")
Exception: Authentication failed
Status code: 500
{"error":"Get \"https://edgeservices.bing.com/edgesvc/turing/conversation/create\": dial tcp: lookup edgeservices.bing.com: too many open files"}
https://edge.churchless.tech/edgesvc/turing/conversation/create

Process finished with exit code 1
```
I got this error. Maybe I need to use proxy. How can I use proxy with EdgeGPT?

### Steps to reproduce the problem

async def bing_chat(prompt):
    gbot = await Chatbot().create()
    response_dict = await gbot.ask(prompt=prompt, conversation_style=ConversationStyle.creative)
    await gbot.close()
    print(response_dict)
    # print(response_dict['item']['messages'][1])
    return response_dict['item']['messages'][1]['text']

text = "01001000 01100101 01101100 01110000 00101100 00100000" \
       "01001001 00100111 01101101 00100000" \
       "01100001 00100000 01101000 01101111 01110011 01110100 01100001 01100111 01100101 00101110"

print(f"None:  {text}")
bot_response = asyncio.run(bing_chat(prompt=text))
print(f"AI:  {bot_response}")
1. Run this code from Russia
2. Get an error

### What should have happened?

The correct response from the Bing AI should have appeared.

### Version where the problem happens

(python -m pip show EdgeGPT)

Name: EdgeGPT
Version: 0.6.10                                
Summary: Reverse engineered Edge Chat API      
Home-page: https://github.com/acheong08/EdgeGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: f:\games\programming_projects\python\telegram_bots\zapzatron_bot\venv\lib\site-packages
Requires: BingImageCreator, certifi, httpx, prompt-toolkit, requests, rich, websockets
Required-by:

### What Python version are you running this with?

Python 3.10.9 (python --version)

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
Нет
```

### Console logs

```Shell
None:  01001000 01100101 01101100 01110000 00101100 0010000001001001 00100111 01101101 0010000001100001 00100000 01101000 01101111 01110011 01110100 01100001 01100111 01100101 00101110
Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 60, in <module>
    bot_response = asyncio.run(bing_chat(prompt=text))
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 48, in bing_chat
    gbot = await Chatbot().create()
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 621, in __init__
    _Conversation(self.proxy, cookies=cookies),
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 343, in __init__
    raise Exception("Authentication failed")
Exception: Authentication failed
Status code: 500
{"error":"Get \"https://edgeservices.bing.com/edgesvc/turing/conversation/create\": dial tcp: lookup edgeservices.bing.com: too many open files"}
https://edge.churchless.tech/edgesvc/turing/conversation/create

Process finished with exit code 1
```

**Comment by acheong08** [comment]
Try again. Perhaps proxy server was hit with ddos

**Comment by Zapzatron** [comment]
I tried to add proxy to "gbot = await Chatbot().create(proxy="https://<proxy>")"

Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 345, in __init__
    self.struct = response.json()
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 60, in <module>
    bot_response = asyncio.run(bing_chat(prompt=text))
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 48, in bing_chat
    gbot = await Chatbot().create(proxy="https://<proxy>")
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 621, in __init__
    _Conversation(self.proxy, cookies=cookies),
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 347, in __init__
    raise Exception(
Exception: Authentication failed. You have not been accepted into the beta.

Process finished with exit code 1

**Comment by Zapzatron** [comment]
EdgeGPT 0.7.1

```python
Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 345, in __init__
    "515vaoprvs",
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\Zapzatron_Bot_WebHook_Async.py", line 718, in bing
    response_text = await bing_chat(text)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\Zapzatron_Bot_WebHook_Async.py", line 678, in bing_chat
    gbot = await Chatbot().create(cookies=cookies)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 621, in __init__
    if obj is None or not obj:
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 347, in __init__
    "kcimgattcf",
Exception: Authentication failed. You have not been accepted into the beta.
```

**Comment by MonsterDruide1** [comment]
Same here. Maybe it is still geo-blocked to only work in *some* places without login?

**Comment by MonsterDruide1** [comment]
Trying to visit `https://www.bing.com/chat` still points me to the "waitlist"-page:
> Chatmodus ist nur verfügbar, wenn Sie Zugriff auf das neue Bing haben.
(Translation: Chat mode is only available if you have access to the new Bing.)

**Comment by Zapzatron** [comment]
I tried using free proxies. For many proxies I got a lot of errors: https://github.com/acheong08/EdgeGPT/issues/465
But some proxies give the same error "Authentication failed. You have not been accepted into the beta."

**Comment by acheong08** [comment]
Documented now. Some IP addresses can't access without authentication
