### ISSUE TITLE
[Bug]: Error : module 'httpx' has no attribute 'AsyncHTTPTransport'

### ISSUE THREAD

**Issue by Caportabow** [acheong08/EdgeGPT#459]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When I runned my code i got this error. I think httpx module does not have an attribute named AsyncHTTPTransport or it is renamed in last versions of this module

### Steps to reproduce the problem

**simply run any code with EdgeGPT or use my example**
```
import asyncio
from EdgeGPT import Chatbot, ConversationStyle

class EdgeGPT:
    def __init__(self):
        self.result = None
        self.question = input('Q:')
        async def get_answer():
            bot = await Chatbot.create()  # Passing cookies is optional
            self.result = await bot.ask(prompt=self.question, conversation_style=ConversationStyle.creative)
            await bot.close()
        asyncio.run(get_answer())
        print(f'A: {self.result}')

if __name__ == "__main__":
    app = EdgeGPT()
    app.mainloop()
```

### What should have happened?

output with
A: answer idk
if you run example code

### Version where the problem happens

0.6.10

### What Python version are you running this with?

3.11.3

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Q:Hello World!
Traceback (most recent call last):
  File "C:\Users\Daniil\PycharmProjects\Iambetterappctk\test.py", line 16, in <module>
    app = EdgeGPT()
          ^^^^^^^^^
  File "C:\Users\Daniil\PycharmProjects\Iambetterappctk\test.py", line 12, in __init__
    asyncio.run(get_answer())
  File "C:\Users\Daniil\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Daniil\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniil\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Daniil\PycharmProjects\Iambetterappctk\test.py", line 9, in get_answer
    bot = await Chatbot.create()  # Passing cookies is optional
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniil\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py", line 634, in create
    await _Conversation.create(self.proxy, cookies=cookies),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniil\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py", line 376, in create
    transport = httpx.AsyncHTTPTransport(retries=900)
                ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'httpx' has no attribute 'AsyncHTTPTransport'

Process finished with exit code 1
```

**Comment by acheong08** [comment]
You might be using an outdated version of httpx or without socks support.

Enforced httpx version: https://github.com/acheong08/EdgeGPT/releases/tag/0.6.11
