### ISSUE TITLE
更新代码后，运行时报错：  "region": locale[-2:],  # en-US -> US TypeError: 'bool' object is not subscriptable，如要怎么处理？

### ISSUE THREAD

**Issue by xiaolvtongxue-zt** [acheong08/EdgeGPT#461]

**Comment by xiaolvtongxue-zt** [comment]
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\gradio\blocks.py", line 882, in call_function
    prediction = await fn(*processed_input)
  File "E:\pythonProjectWork\xiaolv\mew-bing\app.py", line 36, in get_model_reply
    raw_data = await bot.ask(prompt, conversation_style=style)
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\EdgeGPT.py", line 770, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\EdgeGPT.py", line 570, in ask_stream
    self.request.update(
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\EdgeGPT.py", line 354, in update
    "region": locale[-2:],  # en-US -> US
TypeError: 'bool' object is not subscriptable
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000025DF3DAD760>
