### ISSUE TITLE
[Bug]: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

### ISSUE THREAD

**Issue by Zapzatron** [acheong08/EdgeGPT#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

```python
F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\Scripts\python.exe F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py 
None:  Cell number 15 on the 2nd floor! Help me get out!!!
Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 59, in <module>
    bot_response = asyncio.run(bing_chat(prompt=text))
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 48, in bing_chat
    gbot = await Chatbot().create(proxy="https://51.159.0.236:3128")
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 634, in create
    await _Conversation.create(self.proxy, cookies=cookies),
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 391, in create
    response = await client.get(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1754, in get
    return await self.request(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection_pool.py", line 240, in handle_async_request
    response = await connection.handle_async_request(request)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\http_proxy.py", line 261, in handle_async_request
    connect_response = await self._connection.handle_async_request(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection.py", line 141, in _connect
    stream = await stream.start_tls(**kwargs)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
    raise exc
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\backends\asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

Process finished with exit code 1
```

I got this error.

### Steps to reproduce the problem

Run this code:
```python
from EdgeGPT import Chatbot, ConversationStyle
import asyncio


async def bing_chat(prompt):
    gbot = await Chatbot().create(proxy="https://51.159.0.236:3128")
    # gbot = await Chatbot().create()
    response_dict = await gbot.ask(prompt=prompt, conversation_style=ConversationStyle.creative)
    await gbot.close()
    print(response_dict)
    # print(response_dict['item']['messages'][1])
    return response_dict['item']['messages'][1]['text']

text = "Cell number 15 on the 2nd floor! Help me get out!!!"

print(f"None:  {text}")
bot_response = asyncio.run(bing_chat(prompt=text))
print(f"AI:  {bot_response}")
```

### What should have happened?

The correct response from the Bing AI should have appeared.

### Version where the problem happens

Name: EdgeGPT
Version: 0.6.10
Summary: Reverse engineered Edge Chat API      
Home-page: https://github.com/acheong08/EdgeGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org        
License: GNU General Public License v2.0       
Location: f:\games\programming_projects\python\telegram_bots\zapzatron_bot\venv\lib\site-packages
Requires: BingImageCreator, certifi, httpx, prompt-toolkit, requests, rich, websockets
Required-by:

### What Python version are you running this with?

Python 3.10.9 (python --version)

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
Нет
```

### Console logs

```Shell
F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\Scripts\python.exe F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py 
None:  Cell number 15 on the 2nd floor! Help me get out!!!
Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 59, in <module>
    bot_response = asyncio.run(bing_chat(prompt=text))
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 48, in bing_chat
    gbot = await Chatbot().create(proxy="https://51.159.0.236:3128")
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 634, in create
    await _Conversation.create(self.proxy, cookies=cookies),
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 391, in create
    response = await client.get(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1754, in get
    return await self.request(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection_pool.py", line 240, in handle_async_request
    response = await connection.handle_async_request(request)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\http_proxy.py", line 261, in handle_async_request
    connect_response = await self._connection.handle_async_request(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection.py", line 141, in _connect
    stream = await stream.start_tls(**kwargs)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
    raise exc
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\backends\asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

Process finished with exit code 1
```

**Comment by acheong08** [comment]
Proxy issue

**Comment by Zapzatron** [comment]
Tried another proxy
```python
Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\anyio\_core\_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\base_events.py", line 1070, in create_connection
    raise exceptions[0]
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\base_events.py", line 1054, in create_connection
    sock = await self._connect_sock(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\base_events.py", line 963, in _connect_sock
    await self.sock_connect(sock, address)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\proactor_events.py", line 709, in sock_connect
    return await self._proactor.connect(sock, address)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\tasks.py", line 304, in __wakeup
    future.result()
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\windows_events.py", line 821, in _poll
    value = callback(transferred, key, ov)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\windows_events.py", line 608, in finish_connect
    ov.getresult()
OSError: [WinError 121] Превышен таймаут семафора

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\backends\asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\anyio\_core\_sockets.py", line 222, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection_pool.py", line 240, in handle_async_request
    response = await connection.handle_async_request(request)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\http_proxy.py", line 261, in handle_async_request
    connect_response = await self._connection.handle_async_request(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_async\connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\backends\auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\backends\asyncio.py", line 109, in connect_tcp
    with map_exceptions(exc_map):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 62, in <module>
    bot_response = asyncio.run(bing_chat(prompt=text))
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 51, in bing_chat
    gbot = await Chatbot().create(proxy="https://125.136.85.194:7890")
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 634, in create
    await _Conversation.create(self.proxy, cookies=cookies),
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 391, in create
    response = await client.get(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1754, in get
    return await self.request(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
```

**Comment by acheong08** [comment]
Read the error. The proxy isn't accepting connections.
