### ISSUE TITLE
[Bug]: Can't save conversation.

### ISSUE THREAD

**Issue by VMTask** [acheong08/EdgeGPT#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When i trying to call `save_conversation` function,it result this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/EdgeGPT.py", line 734, in save_conversation
    f.write(json.dumps(self.chat_hub.struct))
                       ^^^^^^^^^^^^^^^^^^^^
AttributeError: '_ChatHub' object has no attribute 'struct'
>>> asyncio.run(bot.save_conversation("hist.json"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/EdgeGPT.py", line 734, in save_conversation
    f.write(json.dumps(self.chat_hub.struct))
                       ^^^^^^^^^^^^^^^^^^^^
AttributeError: '_ChatHub' object has no attribute 'struct'
```

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

Save the conversation to a file.

### Version where the problem happens

0.8.2

### What Python version are you running this with?

Python 3.11.3

### What is your operating system ?

Linux, Android

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Python 3.11.3 (main, Apr  7 2023, 00:39:07) [Clang 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json,asyncio,EdgeGPT
>>> with open("cookies.json") as f:
...     cookie=json.load(f)
...
>>> bot = asyncio.run(EdgeGPT.Chatbot.create(cookies=cookie))
>>> ans = asyncio.run(bot.ask(prompt="你好",conversation_style="balanced"))
>>> and
  File "<stdin>", line 1
    and
    ^^^
SyntaxError: invalid syntax
>>> ans
{'type': 2, 'invocationId': '0', 'item': {'messages': [{'text': '你好', 'author': 'user', 'from': {'id': '914799412008574', 'name': None}, 'createdAt': '2023-06-05T11:35:43.0393782+00:00', 'timestamp': '2023-06-05T11:35:43.0339458+00:00', 'locale': 'en-US', 'market': 'en-US', 'region': 'US', 'locationHints': [{'country': 'United States', 'countryConfidence': 8, 'state': 'California', 'city': 'Los Angeles', 'timeZoneOffset': 8, 'sourceType': 1, 'center': {'latitude': 34.05369, 'longitude': -118.24277, 'height': None}, 'regionType': 2}], 'messageId': '7b889f32-c17d-4de2-8909-93be054f2f9f', 'requestId': '7b889f32-c17d-4de2-8909-93be054f2f9f', 'nlu': {'scoredClassification': {'classification': 'DEEP_LEO', 'score': None}, 'classificationRanking': [{'classification': 'DEEP_LEO', 'score': None}], 'qualifyingClassifications': None, 'ood': None, 'metaData': None, 'entities': None}, 'offense': 'None', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'cib', 'privacy': None, 'inputMethod': 'Keyboard'}, {'text': '你好，这里是必应。我可以用中文和你交流。😊', 'author': 'bot', 'createdAt': '2023-06-05T11:35:56.0524454+00:00', 'timestamp': '2023-06-05T11:35:56.0524454+00:00', 'messageId': '7baaa4a2-915d-4d28-b024-2f24879b5c61', 'requestId': '7b889f32-c17d-4de2-8909-93be054f2f9f', 'offense': 'None', 'adaptiveCards': [{'type': 'AdaptiveCard', 'version': '1.0', 'body': [{'type': 'TextBlock', 'text': '你好，这里是必应。我可以用中文和你交流。😊\n', 'wrap': True}]}], 'sourceAttributions': [], 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'DeepLeo', 'privacy': None, 'suggestedResponses': [{'text': '你能告诉我一些关于必应的 事情吗？', 'author': 'user', 'createdAt': '2023-06-05T11:35:59.6759456+00:00', 'timestamp': '2023-06-05T11:35:59.6759456+00:00', 'messageId': 'f50e685a-1aa8-4296-b2a4-f33a906c5906', 'messageType': 'Suggestion', 'offense': 'Unknown', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'SuggestionChipsFalconService', 'privacy': None}, {'text': '请问您有什么问题需要帮忙解答吗？', 'author': 'user', 'createdAt': '2023-06-05T11:35:59.6759468+00:00', 'timestamp': '2023-06-05T11:35:59.6759468+00:00', 'messageId': '7298d655-c87f-4561-8dc3-9786b3fbba66', 'messageType': 'Suggestion', 'offense': 'Unknown', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'SuggestionChipsFalconService', 'privacy': None}, {'text': '你会说其他语言吗?', 'author': 'user', 'createdAt': '2023-06-05T11:35:59.6759472+00:00', 'timestamp': '2023-06-05T11:35:59.6759472+00:00', 'messageId': '62b3ba38-f1ae-42de-baef-06bff6207f9d', 'messageType': 'Suggestion', 'offense': 'Unknown', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'SuggestionChipsFalconService', 'privacy': None}]}], 'firstNewMessageIndex': 1, 'defaultChatName': None, 'conversationId': '51D|BingProd|8A2FE029F0F42A0D0BD038420390FFC177005E07F53C9EAA9EEBCF4879ECA73B', 'requestId': '7b889f32-c17d-4de2-8909-93be054f2f9f', 'conversationExpiryTime': '2023-06-05T17:35:59.695034Z', 'shouldInitiateConversation': True, 'telemetry': {'metrics': None, 'startTime': '2023-06-05T11:35:43.0340741Z'}, 'throttling': {'maxNumUserMessagesInConversation': 30, 'numUserMessagesInConversation': 1}, 'result': {'value': 'Success', 'message': '你好，这里是必应。我可以用中文和你交流 。😊', 'serviceVersion': '20230605.2'}}}
>>> asnycio.run(bot.save_conversation())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'asnycio' is not defined. Did you mean: 'asyncio'?
>>> asyncio.run(bot.save_conversation("hist.json"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/EdgeGPT.py", line 734, in save_conversation
    f.write(json.dumps(self.chat_hub.struct))
                       ^^^^^^^^^^^^^^^^^^^^
AttributeError: '_ChatHub' object has no attribute 'struct'
>>> asyncio.run(bot.save_conversation("hist.json"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/EdgeGPT.py", line 734, in save_conversation
    f.write(json.dumps(self.chat_hub.struct))
                       ^^^^^^^^^^^^^^^^^^^^
AttributeError: '_ChatHub' object has no attribute 'struct'
>>> asyncio.run(bot.save_conversation("hist.json"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/EdgeGPT.py", line 734, in save_conversation
    f.write(json.dumps(self.chat_hub.struct))
                       ^^^^^^^^^^^^^^^^^^^^
AttributeError: '_ChatHub' object has no attribute 'struct'
>>>
```

**Comment by acheong08** [comment]
working on it. already fixed on latest commit but caused other bugs

**Comment by acheong08** [comment]
Oops. Wait for next release. Noticed another bug
