### ISSUE TITLE
'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by Eikosa** [acheong08/EdgeGPT#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

```python3
Traceback (most recent call last):
  File "/root/Bot/__main__.py", line 565, in bing
    get_response = await bot.ask(prompt=prompt, conversation_style=ConversationStyle.creative)
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 745, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 596, in ask_stream
    objects = msg.data.split(DELIMITER)
AttributeError: 'NoneType' object has no attribute 'split'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Bot/__main__.py", line 565, in bing
    get_response = await bot.ask(prompt=prompt, conversation_style=ConversationStyle.creative)
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 745, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 596, in ask_stream
    objects = msg.data.split(DELIMITER)
AttributeError: 'NoneType' object has no attribute 'split'
```

### Steps to reproduce the problem

?

### What should have happened?

No error

### Version where the problem happens

Name: EdgeGPT
Version: 0.7.2

### What Python version are you running this with?

3.10

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
.
```

**Comment by acheong08** [comment]
I just got a similar issue. No response anymore for some reason

**Comment by acheong08** [comment]
Not sure if they are able to detect us somehow and just not respond?

**Comment by acheong08** [comment]
Try 0.9.0

**Comment by phamxtien** [comment]
Still get error: 'int' object has no attribute 'split'

**Comment by phamxtien** [comment]
Try 0.9.1 still get error: 'int' object has no attribute 'split'

**Comment by phamxtien** [comment]
Try 0.10.2 still get error: 'int' object has no attribute 'split'

**Comment by fcgca** [comment]
0.10.3, python 3.11, get error: 

AttributeError: 'int' object has no attribute 'split'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10436a110>

-----

File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/flyabroadca/github/regulations_ca/bing_framework.py", line 265, in main
    print(await bot.ask(prompt=the_prompt, conversation_style=ConversationStyle.creative))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/flyabroadca/github/chatgpt/lib/python3.11/site-packages/EdgeGPT/EdgeGPT.py", line 98, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/Users/flyabroadca/github/chatgpt/lib/python3.11/site-packages/EdgeGPT/chathub.py", line 108, in ask_stream
    objects = msg.data.split(DELIMITER)
              ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10436a110>

**Comment by loby66** [comment]
same error, only with "--style creative" parameter

**Comment by sfknhagvkas** [comment]
It returns error for me every time when the prompt is longer then 16 symbols.

<details>
<summary>Terminal Log</summary>

```
~ 〉bing 12345678901234567890
AttributeError: 'int' object has no attribute 'split'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff51474e0d0>

~ 〉bing 1234567890123456789
AttributeError: 'int' object has no attribute 'split'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f43d9d702d0>

~ 〉bing 123456789012345678
AttributeError: 'int' object has no attribute 'split'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd799e25390>

~ 〉bing 12345678901234567
AttributeError: 'int' object has no attribute 'split'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2d6e327090>

~ 〉bing 1234567890123456
That's a long number. Is it a credit card number?

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fbc0dac4a50>

~ 〉bing 12345678901234567
AttributeError: 'int' object has no attribute 'split'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f01f05c5550>

~ 〉bing 1234567890123456
That's a long number. Is it a credit card number?

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7efddb19d350>

~ 〉bing 12345678901234567
AttributeError: 'int' object has no attribute 'split'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe0f87b0f90>

~ 〉bing 1234567890123456
That looks like a 16-digit number. Is there a reason you typed that?

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f45b6d6d690>

~ 〉bing 12345678901234567
AttributeError: 'int' object has no attribute 'split'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6566509d10>

~ 〉bing 1234567890123456
That's a long number. Is it your credit card number?😉

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb4b0ca0410>

```
</details>


<details>
<summary>JSON dump</summary>

```json
{
    "type": 2,
    "invocationId": "3",
    "item": {
        "messages": [
            {
                "text": "1234567890123456",
                "author": "user",
                "from": {
                    "id": "3C4130273CF063FC1603230D3DC362C1",
                    "name": null
                },
                "createdAt": "2023-06-08T08:28:46.949906+00:00",
                "timestamp": "2023-06-08T11:29:22+02:59",
                "locale": "en-US",
                "market": "en-US",
                "region": "US",
                "locationHints": [
                    {
                        "country": "United States",
                        "countryConfidence": 8,
                        "state": "California",
                        "city": "Los Angeles",
                        "timeZoneOffset": 8,
                        "sourceType": 1,
                        "center": {
                            "latitude": 34.05369,
                            "longitude": -118.24277,
                            "height": null
                        },
                        "regionType": 2
                    }
                ],
                "messageId": "0b0cc1bd-df0a-44c2-8a31-011c3992aaeb",
                "requestId": "0b0cc1bd-df0a-44c2-8a31-011c3992aaeb",
                "nlu": {
                    "scoredClassification": {
                        "classification": "DEEP_LEO",
                        "score": null
                    },
                    "classificationRanking": [
                        { "classification": "DEEP_LEO", "score": null }
                    ],
                    "qualifyingClassifications": null,
                    "ood": null,
                    "metaData": null,
                    "entities": null
                },
                "offense": "None",
                "feedback": { "tag": null, "updatedOn": null, "type": "None" },
                "contentOrigin": "cib",
                "privacy": null,
                "inputMethod": "Keyboard"
            },
            {
                "text": "That's a long number. Is it your credit card number?\ud83d\ude09",
                "author": "bot",
                "createdAt": "2023-06-08T08:28:57.9394716+00:00",
                "timestamp": "2023-06-08T08:28:57.9394716+00:00",
                "messageId": "d0387584-fac7-4ad7-9dc5-95202713df08",
                "requestId": "0b0cc1bd-df0a-44c2-8a31-011c3992aaeb",
                "offense": "None",
                "adaptiveCards": [
                    {
                        "type": "AdaptiveCard",
                        "version": "1.0",
                        "body": [
                            {
                                "type": "TextBlock",
                                "text": "That's a long number. Is it your credit card number?\ud83d\ude09\n",
                                "wrap": true
                            }
                        ]
                    }
                ],
                "sourceAttributions": [],
                "feedback": { "tag": null, "updatedOn": null, "type": "None" },
                "contentOrigin": "DeepLeo",
                "privacy": null,
                "suggestedResponses": [
                    {
                        "text": "No, it's not.",
                        "author": "user",
                        "createdAt": "2023-06-08T08:29:05.4017775+00:00",
                        "timestamp": "2023-06-08T08:29:05.4017775+00:00",
                        "messageId": "5c120f98-2b29-4816-a8ee-2bda003d0dd7",
                        "messageType": "Suggestion",
                        "offense": "Unknown",
                        "feedback": {
                            "tag": null,
                            "updatedOn": null,
                            "type": "None"
                        },
                        "contentOrigin": "DeepLeo",
                        "privacy": null
                    },
                    {
                        "text": "Yes, it is. Do you want it?",
                        "author": "user",
                        "createdAt": "2023-06-08T08:29:05.4017829+00:00",
                        "timestamp": "2023-06-08T08:29:05.4017829+00:00",
                        "messageId": "ee0a0194-a4fa-43d9-9fec-a4307bddae29",
                        "messageType": "Suggestion",
                        "offense": "Unknown",
                        "feedback": {
                            "tag": null,
                            "updatedOn": null,
                            "type": "None"
                        },
                        "contentOrigin": "DeepLeo",
                        "privacy": null
                    },
                    {
                        "text": "Actually, it's a secret code.",
                        "author": "user",
                        "createdAt": "2023-06-08T08:29:05.4017834+00:00",
                        "timestamp": "2023-06-08T08:29:05.4017834+00:00",
                        "messageId": "ca99b2c5-58ee-48a8-82a9-16550ff6475f",
                        "messageType": "Suggestion",
                        "offense": "Unknown",
                        "feedback": {
                            "tag": null,
                            "updatedOn": null,
                            "type": "None"
                        },
                        "contentOrigin": "DeepLeo",
                        "privacy": null
                    }
                ],
                "spokenText": "Is it your credit card number?"
            }
        ],
        "firstNewMessageIndex": 1,
        "defaultChatName": "1234567890123456",
        "conversationId": "51D|BingProd|E5A16B6F7964D4AC8008B985288B000A1068CBE674C55F41E1D5C036938B6ADB",
        "requestId": "0b0cc1bd-df0a-44c2-8a31-011c3992aaeb",
        "conversationExpiryTime": "2023-09-06T08:29:05.7216066Z",
        "shouldInitiateConversation": true,
        "telemetry": {
            "metrics": null,
            "startTime": "2023-06-08T08:28:46.945739Z"
        },
        "throttling": {
            "maxNumUserMessagesInConversation": 5,
            "numUserMessagesInConversation": 1
        },
        "result": {
            "value": "Success",
            "message": "1234567890123456",
            "serviceVersion": "20230607.139"
        }
    }
}
```

</details>
