### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by IbrahimLakhzine** [acheong08/EdgeGPT#50]
Initializing...
Traceback (most recent call last):
  File "C:\Users\ibrahim.l\Desktop\MicroEdgeGPT.py", line 61, in <module>
    asyncio.run(main())
  File "C:\Users\ibrahim.l\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ibrahim.l\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\ibrahim.l\Desktop\MicroEdgeGPT.py", line 33, in main
    bot = Chatbot()
  File "C:\Users\ibrahim.l\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 213, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation())
  File "C:\Users\ibrahim.l\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 113, in __init__
    open(os.environ.get("COOKIE_FILE"), "r", encoding="utf-8").read()
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by GrahamboJangles** [comment]
Same problem. Is there no longer a public token?

**Comment by acheong08** [comment]
> Same problem. Is there no longer a public token?

Yes. Public token got revoked
