### ISSUE TITLE
[Bug]: Cannot load, I get an error

### ISSUE THREAD

**Issue by juangea** [acheong08/EdgeGPT#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I updated Oobabooga and it stope activating the extension, here is the error:

Traceback (most recent call last):
  File "D:\AI\oobabooga\oobabooga_windows\text-generation-webui\modules\extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\AI\oobabooga\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 7, in <module>
    from EdgeGPT import Chatbot, ConversationStyle
ImportError: cannot import name 'Chatbot' from 'EdgeGPT' (D:\AI\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\EdgeGPT\__init__.py)

Maybe something changed?

### Steps to reproduce the problem

Update Oobabooga and it should stop loading

### What should have happened?

It should have loaded normally

### Version where the problem happens

Latest version of EdgeGPT and Oobabooga (07/06/2023)

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "D:\AI\oobabooga\oobabooga_windows\text-generation-webui\modules\extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\AI\oobabooga\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 7, in <module>
    from EdgeGPT import Chatbot, ConversationStyle
ImportError: cannot import name 'Chatbot' from 'EdgeGPT' (D:\AI\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\EdgeGPT\__init__.py)
```

**Comment by phamxtien** [comment]
from EdgeGPT import Chatbot, ConversationStyle

to 

from EdgeGPT.EdgeGPT import Chatbot, ConversationStyle

**Comment by acheong08** [comment]
I will open PR

**Comment by acheong08** [comment]
https://github.com/GiusTex/EdgeGPT/pull/14
