### ISSUE TITLE
[Bug]: AttributeError:int' object has no attribute 'split!  in chathub.py line 115

### ISSUE THREAD

**Issue by kang121209** [acheong08/EdgeGPT#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

<img width="609" alt="119c461a756785364170c3d0770e176" src="https://github.com/acheong08/EdgeGPT/assets/127708228/b5ae16af-202a-4e0a-8df6-c9db427307de">

### Steps to reproduce the problem

1、use ask_stream function,exception AttributeError:int' object has no attribute 'split!  in chathub.py line 115

### What should have happened?

use ask_stream function,exception AttributeError:int' object has no attribute 'split!  in chathub.py line 115

### Version where the problem happens

python3.10

### What Python version are you running this with?

python3.10

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
use ask_stream function,exception AttributeError:int' object has no attribute 'split!  in chathub.py line 115
```

**Comment by qust1n** [comment]
Show response data

**Comment by kang121209** [comment]
i add code like this:
            try:
                objects = msg.data.split(DELIMITER)
            except Exception as e:
                raise Exception("except data: ",msg.data)


   async for chunk in self.body_iterator:
  File "/data/web/xiezuo.gptlala.com/aiboxs/api/common.py", line 86, in generate
    async for c in massage:
  File "/usr/local/lib/python3.10/site-packages/EdgeGPT/EdgeGPT.py", line 132, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.10/site-packages/EdgeGPT/chathub.py", line 118, in ask_stream
    raise Exception("except data: ",msg.data)
Exception: ('except data: ', 1000)


msg.data value is 1000, int type.

**Comment by kang121209** [comment]
[2023-06-09 18:14:02 +0800] [117720] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/data/web/xiezuo.gptlala.com/aiboxs/api/common.py", line 86, in generate
    async for c in massage:
  File "/usr/local/lib/python3.10/site-packages/EdgeGPT/EdgeGPT.py", line 132, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.10/site-packages/EdgeGPT/chathub.py", line 85, in ask_stream
    self.wss = await self.wss_session.ws_connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 502, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')

when bing 502,can auto retry?

**Comment by acheong08** [comment]
Should be fixed
