### ISSUE TITLE
If some one is having the error key error 'adaptiveCards' even after fix #559 then try this

### ISSUE THREAD

**Issue by Meshwa428** [acheong08/EdgeGPT#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Its just a fix that i was facing with simplify_response.
Even after setting it to true and i was trying to get the ["text"] but some times it gave me the error

KeyError: 'adaptiveCards'

I also request @acheong08 to take a look at this

### Proposed workflow

None

### Additional information

Just go to EdgeGPT.py

 and look for
         async for final, response in self.chat_hub.ask_stream

and replace it till return{} with this code and you are good to go

 
         async for final, response in self.chat_hub.ask_stream(
            prompt=prompt,
            conversation_style=conversation_style,
            wss_link=wss_link,
            webpage_context=webpage_context,
            search_result=search_result,
            locale=locale,
        ):
            if final:
                if not simplify_response:
                    return response
                message = next(
                    (
                        s
                        for s in reversed(response["item"]["messages"])
                        if "messageType" not in s
                    ),
                    response["item"]["messages"][-1],
                )
                suggestions = [
                    suggestion["text"]
                    for suggestion in message.get("suggestedResponses", [])
                ]
                adaptive_cards = message.get("adaptiveCards", [])
                adaptive_text = adaptive_cards[0]["body"][0].get("text") if adaptive_cards else None
                sources = adaptive_cards[0]["body"][0].get("text") if adaptive_cards else None
                sources_text = adaptive_cards[0]["body"][-1].get("text") if adaptive_cards else None
                return {
                    "text": message["text"],
                    "author": message["author"],
                    "sources": sources,
                    "sources_text": sources_text,
                    "suggestions": suggestions,
                    "messages_left": response["item"]["throttling"][
                        "maxNumUserMessagesInConversation"
                    ]
                    - response["item"]["throttling"].get("numUserMessagesInConversation", 0),
                    "adaptive_text": adaptive_text,
                }
        return {}

**Comment by Meshwa428** [comment]
The code i use

```
import asyncio, json, re
from EdgeGPT.EdgeGPT import Chatbot, ConversationStyle

cookies = json.loads(open("Data/cookies.json", encoding="utf-8").read())

# Main function to get the response from EdgeGPT
async def edgegpt(prompt):
    bot = await Chatbot.create(cookies=cookies)

    # Loading the conversation
    await bot.load_conversation(filename="Data/bing_history.json")

    # Getting the response from Bing
    response = await bot.ask(prompt=prompt, conversation_style=ConversationStyle.creative, simplify_response=True)
    response = json.loads(json.dumps(response, indent=2))

    # Saving the conversation
    await bot.save_conversation(filename="Data/bing_history.json")
    final_text = response["text"]

    pattern = r'\[\^\d+\^\]'
    final_text = re.sub(pattern, '', final_text)
    await bot.close()
    return final_text
```

## The Error I get

```
You : can you tell me some latest news just the summary.
Traceback (most recent call last):
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 92, in <module>
    ClapDetect()
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 88, in ClapDetect
    MainExecution()
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 70, in MainExecution
    Reply = asyncio.run(edgegpt(Data))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Brain\Qna.py", line 14, in edgegpt
    response = await bot.ask(prompt=prompt, conversation_style=ConversationStyle.creative, simplify_response=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 139, in ask
    "sources_text": message["adaptiveCards"][0]["body"][-1]["text"],
                    ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'adaptiveCards'
```
