### ISSUE TITLE
Shows [UnboundLocalError: cannot access local variable 'message' where it is not associated with a value] after few conversations

### ISSUE THREAD

**Issue by Meshwa428** [acheong08/EdgeGPT#571]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What happened?

It shows the error after a few conversations, I think it might be with my code

### What should have happened?

I don't know

### Version where the problem happens

Version: 0.11.6

### What Python version are you running this with?

3.11.3

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
None
```

### Console logs

```Shell
Traceback (most recent call last):
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 92, in <module>
    ClapDetect()
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 88, in ClapDetect
    MainExecution()
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 70, in MainExecution
    Reply = asyncio.run(edgegpt(Data))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Brain\Qna.py", line 14, in edgegpt
    response = await bot.ask(prompt=prompt, conversation_style=ConversationStyle.creative, simplify_response=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 135, in ask
    for suggestion in message.get("suggestedResponses", [])
                      ^^^^^^^
UnboundLocalError: cannot access local variable 'message' where it is not associated with a value
```

## My Code

```Python
import asyncio, json, re
from EdgeGPT.EdgeGPT import Chatbot, ConversationStyle

cookies = json.loads(open("Data/cookies.json", encoding="utf-8").read())

# Main function to get the response from EdgeGPT
async def edgegpt(prompt):
    bot = await Chatbot.create(cookies=cookies)

    # Loading the conversation
    await bot.load_conversation(filename="Data/bing_history.json")

    # Getting the response from Bing
    response = await bot.ask(prompt=prompt, conversation_style=ConversationStyle.creative, simplify_response=True)
    response = json.dumps(response, indent=2)

    # Saving the conversation
    await bot.save_conversation(filename="Data/bing_history.json")
    final_text = response["text"]

    # This is just for removing [^1^] kind of things from the response
    pattern = r'\[\^\d+\^\]'
    final_text = re.sub(pattern, '', final_text)
    await bot.close()
    return final_text
```

**Comment by Meshwa428** [comment]
This happens after there are 0 message left, so is there any way to increase the amount of chats we can do, like its 30 by default right, can we increase it, or is there a way to bypass it so that we can continue the conversation

**Comment by txAnnie** [comment]
How to solve this problem? I meet the same one.
