### ISSUE TITLE
[Bug]: using edgegpt without cookies sometimes doesn't work

### ISSUE THREAD

**Issue by Cod3on3** [acheong08/EdgeGPT#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I sometimes get an error while using EdgeGPT without cookies. I am sure it isn't because I have used the 10 messages. how do i solve this?
```
bing.py
Enter a prompt: hi
Traceback (most recent call last):
  File "c:\path to\autobing.py", line 19, in <module>
    asyncio.run(main())  # Run the main asynchronous function
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\path to\autobing.py", line 14, in main
    response_text = await prompt(prompt_text)  # Run the prompt task with the provided prompt text       
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\path to\autobing.py", line 6, in prompt
    bot = await Chatbot.create()  # Create an instance of the Chatbot
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\path to\EdgeGPT.py", line 42, in create
    await Conversation.create(self.proxy, cookies=cookies),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\path to\conversation.py", line 121, in create
    raise NotAllowedToAccess(self.struct["result"]["message"])
EdgeGPT.exceptions.NotAllowedToAccess: Sorry, you need to login first to access this service.
```

### Steps to reproduce the problem

Use EdgeGPT a bunch of times without passing in cookies and you will get this error. 

### What should have happened?

Bing should have responded

### Version where the problem happens

0.11.6

### What Python version are you running this with?

Python 3.11.4

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
.
```

**Comment by acheong08** [comment]
Expected.
