### ISSUE TITLE
[Bug]: Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.

### ISSUE THREAD

**Issue by a37836323** [acheong08/EdgeGPT#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

After using it 30 times, it prompts this, what should I do?

### Steps to reproduce the problem

1. After using it 30 times, it prompts this, what should I do?

### What should have happened?

After using it 30 times, it prompts this, what should I do?

### Version where the problem happens

3.9

### What Python version are you running this with?

3.9

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/www/wwwroot/ceshi701/EdgeGPT/bbb.py", line 31, in chat
    responses = loop.run_until_complete(get_responses())
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/www/wwwroot/ceshi701/EdgeGPT/bbb.py", line 18, in get_responses
    async for final, response in bot.ask_stream(prompt=question, conversation_style=ConversationStyle.creative):
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/EdgeGPT/EdgeGPT.py", line 185, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/EdgeGPT/chathub.py", line 197, in ask_stream
    raise Exception(
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
[2023-07-02 01:31:19,185] ERROR in app: Exception on /chat [POST]
Traceback (most recent call last):
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/www/wwwroot/ceshi701/EdgeGPT/bbb.py", line 31, in chat
    responses = loop.run_until_complete(get_responses())
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/www/wwwroot/ceshi701/EdgeGPT/bbb.py", line 18, in get_responses
    async for final, response in bot.ask_stream(prompt=question, conversation_style=ConversationStyle.creative):
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/EdgeGPT/EdgeGPT.py", line 185, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/EdgeGPT/chathub.py", line 197, in ask_stream
    raise Exception(
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
```

### Additional information

ok

**Comment by kang121209** [comment]
mee too

**Comment by Meshwa428** [comment]
Same here, when ever i try to create a new conversation it shows this error
```Shell
Traceback (most recent call last):
  File "p:\Python\J.A.R.V.I.S\Jarvis Using Python\Brain\Qna.py", line 63, in <module>
    name = Qna()
           ^^^^^
  File "p:\Python\J.A.R.V.I.S\Jarvis Using Python\Brain\Qna.py", line 60, in Qna
    app = asyncio.run(Starting_prompt(data))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete        
    return future.result()
           ^^^^^^^^^^^^^^^
  File "p:\Python\J.A.R.V.I.S\Jarvis Using Python\Brain\Qna.py", line 40, in Starting_prompt
    response = await bot1.ask(prompt=prompt, conversation_style=ConversationStyle.creative, simplify_response=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 116, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\chathub.py", line 197, in ask_stream      
    raise Exception(
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
```

**Comment by Eikosa** [comment]
I solve this problem by using a proxy

**Comment by adekability** [comment]
> I solve this problem by using a proxy

@Eikosa , hello! Which country did you use as a proxy server location?

**Comment by Eikosa** [comment]
> > I solve this problem by using a proxy
> 
> @Eikosa , hello! Which country did you use as a proxy server location?

I try with the https://pypi.org/project/free-proxy/ module until I find a suitable https proxy, one of them always works

**Comment by Meshwa428** [comment]
Is it possible to create a captcha solver, so that we don't have to use a proxy, by the way there is another way to solve this issue. Before running your script you can just go to bing.com/chat and then it will automatically solve the captcha then you can run your script, and it will work as good as new

**Comment by acheong08** [comment]
What does the captcha look like? Is it arkose/funcaptcha? I haven't triggered it yet so can't fix. If it is indeed arkose/funcaptcha, I got it reversed at https://github.com/acheong08/funcaptcha

**Comment by YonQua** [comment]
<img width="1475" alt="WechatIMG202" src="https://github.com/acheong08/EdgeGPT/assets/18325417/913f1d42-59d9-40f0-99ca-3751914b93f9">
User needs to solve CAPTCHA to continue.

**Comment by Eikosa** [comment]
I'm sorry to say that using a proxy doesn't seem to solve this problem anymore

**Comment by DreamMaoMao** [comment]
Has there been any progress on this issue

**Comment by plageon** [comment]
also met this problem

**Comment by wangyu1997** [comment]
me too

**Comment by mayuqianjg** [comment]
Me three

**Comment by ProfDrLuigi** [comment]
Me four

**Comment by Qewertyy** [comment]
Me five

**Comment by wangyu1997** [comment]
Interesting。。。

**Comment by DrowskoytayhulGuider** [comment]
> Interesting。。。

I want to ask how do you use it? I always got a problem:  raise TooManyRedirects(
httpx.TooManyRedirects: Exceeded maximum allowed redirects.

**Comment by wangyu1997** [comment]
> > Interesting。。。
> 
> I want to ask how do you use it? I always got a problem: raise TooManyRedirects( httpx.TooManyRedirects: Exceeded maximum allowed redirects.

You can use a us proxy or directly deploy on a us machine

**Comment by DrowskoytayhulGuider** [comment]
> > > Interesting。。。
> > 
> > 
> > I want to ask how do you use it? I always got a problem: raise TooManyRedirects( httpx.TooManyRedirects: Exceeded maximum allowed redirects.
> 
> 您可以使用美国代理或直接部署在美国计算机上

You mean I need to get a valid US proxy IP and add it in "--proxy" parameter? I have to build a proxy pool?

**Comment by nacho00112** [comment]
The free-proxy library give proxies but they don't worked for me:
```
from fp.fp import FreeProxy
import json
proxy = FreeProxy().get()
cookies = json.load(open("cookies.json"))
bot = Chatbot.create(cookies=cookies, proxy=proxy)
```
I get SSL Verification failed or Captcha error

**Comment by Eikosa** [comment]
> The free-proxy library give proxies but they doesn't worked for me:
> 
> ```python
> from EdgeGPT.EdgeGPT import Chatbot
> from fp.fp import FreeProxy
> 
> import json, asyncio
> 
> async def main():
>     proxy = FreeProxy().get()
>     cookies = json.load(open("cookies.json"))
>     bot = await Chatbot.create(cookies=cookies, proxy=proxy)
>     response = bot.ask(prompt="hello")
>     print(response)
> if __name__ == "__main__":
>     asyncio.run(main())
> ```
> 
> I get SSL Verification failed or Captcha error

use freeproxy with https, it is unlikely, but sometimes it works

**Comment by DrowskoytayhulGuider** [comment]
> The free-proxy library give proxies but they doesn't worked for me:
> 
> ```python
> from EdgeGPT.EdgeGPT import Chatbot
> from fp.fp import FreeProxy
> 
> import json, asyncio
> 
> async def main():
>     proxy = FreeProxy().get()
>     cookies = json.load(open("cookies.json"))
>     bot = await Chatbot.create(cookies=cookies, proxy=proxy)
>     response = bot.ask(prompt="hello")
>     print(response)
> if __name__ == "__main__":
>     asyncio.run(main())
> ```
> 
> I get SSL Verification failed or Captcha error

When I use free proxies, I often get SSL Verification failed, too. And sometimes I also get "all connections failed." and "connectError"

**Comment by DrowskoytayhulGuider** [comment]
> 

I tried many free proxies, but all didn't work.

**Comment by watashihame** [comment]
I'm using [gpt_academic](https://github.com/binary-husky/gpt_academic/tree/master) and I met the same problem.
My solution is modified the user-agent and other information showed in [this file](https://github.com/binary-husky/gpt_academic/blob/master/request_llm/edge_gpt_free.py). You can try the instruction below:

1. Using the exactly same header as your browser (Mircrosoft edge), including user-agent and browser version informaiton.
2. Using your code to ask any question (normally you will get the exception as this issue said).
3. Using your browser to ask any question with new bing (manually solve the captcha).
4. Free to use your code to ask with new bing.

**Comment by tianlichunhong** [comment]
I have the same problem.The only temporary fix I can come up with at the moment is to log in and visit new bing via the edge browser,  and click the CAPTCHA. This can let my edgeGPT work for one day.

**Comment by Meshwa428** [comment]
same i have to do this process before running the script and it lets me use it for 1 day, just open edge browser and then solve the captcha it manualy, and then it lets me do the job done

**Comment by ustedestaaqui** [comment]
> same i have to do this process before running the script and it lets me use it for 1 day, just open edge browser and then solve the captcha it manualy, and then it lets me do the job done

But when I open the browser no captcha appears

**Comment by ustedestaaqui** [comment]
> I have the same problem.The only temporary fix I can come up with at the moment is to log in and visit new bing via the edge browser, and click the CAPTCHA. This can let my edgeGPT work for one day.

But when I open the browser no captcha appears

**Comment by tianlichunhong** [comment]
> > I have the same problem.The only temporary fix I can come up with at the moment is to log in and visit new bing via the edge browser, and click the CAPTCHA. This can let my edgeGPT work for one day.
> 
> But when I open the browser no captcha appears

You need to ask a question, then you can see the captcha.

**Comment by ustedestaaqui** [comment]
> 

but when I enter from the web it does not ask me for any captcha, I can chat normally

**Comment by Meshwa428** [comment]
Then you are good to go, you can run your script

**Comment by nacho00112** [comment]
Might be this error is related with VPNs, you used a VPN?

**Comment by ProfDrLuigi** [comment]
If you are running a Linux Desktop Environment I solved it now this way. Install Microsoft Edge and xdotool. Start Edge, log into your M$ Account and select saving the credentials for the next browser start. If done you can now execute this snippet here automatic via cron.

`microsoft-edge & sleep 10 && xdotool key H && xdotool key i && xdotool key KP_Enter && sleep 10 && xdotool key ctrl+w`

It sends "Hi" to the Bot and the Verification capture is done. After refresehing the session the Browser quits automatic.

**Comment by Meshwa428** [comment]
Thanks for the help, but we windows users have to do that stuff manualy or in WSL, i think automating it with selenium might be a good idea, I mean we can use selenium to automate edge browser. Just log in to it, send a hi to bing and done. I am starting to work on it, after i complete i will provide the code snippet here

**Comment by ustedestaaqui** [comment]
> Thanks for the help, but we windows users have to do that stuff manualy or in WSL, i think automating it with selenium might be a good idea, I mean we can use selenium to automate edge browser. Just log in to it, send a hi to bing and done. I am starting to work on it, after i complete i will provide the code snippet here

I was trying to program it in selenium but I couldn't do the code with bing hahaha

**Comment by nacho00112** [comment]
> I fix it by request to https://www.bing.com/turing/conversation/create and get conversationSignature import requests and add newlines
> 
> ![image](https://user-images.githubusercontent.com/33739597/255139282-1d775e68-ed6e-48ae-b06b-0577677fcbae.png)

Then please make the PR

**Comment by nacho00112** [comment]
I checked `Conversation` and it already makes that request and set `struct` to the whole json but uses a different url: `https://edgeservices.bing.com/edgesvc/turing/conversation/create`

**Comment by ProfDrLuigi** [comment]
> I fix it by request to https://www.bing.com/turing/conversation/create and get conversationSignature import requests and add newlines
> 
Doesn´t work here.

**Comment by phamxtien** [comment]
Today, I got 503, 
I back to previous code (remove https://www.bing.com/turing/conversation/create) and it runs smooth

**Comment by phamxtien** [comment]
Now it require CAPTCHA :(

**Comment by phamxtien** [comment]
I am not sure but after change lines 20, 21 in constant.py to
"sec-ch-ua-full-version": '"116.0.1938.27"',
"sec-ch-ua-full-version-list": '"Chromium";v="116.0.5845.42", "Not)A;Brand";v="24.0.0.0", "Microsoft Edge";v="116.0.1938.27"', 

![image](https://github.com/acheong08/EdgeGPT/assets/33739597/e3c34262-b4d3-44b8-a464-9912b0b37aad)

and it runs smooth.

**Comment by Meshwa428** [comment]
This code sort of fixed my issue. I am using bard and EdgeGPT together, so i was going for that. In this code what it does is, it just logs in to your account and goes to bing.com and extracts cookies every 2 or 3 days and stores them in a file, and this refreshing of cookies allowed me to solve the issue

```python
import datetime
import json
import os
import logging
from time import sleep

from selenium import webdriver
from selenium.webdriver.chrome.options import Options as ChromeOptions
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.edge.options import Options as EdgeOptions

chrm_usr_data = r"p:\Python\J.A.R.V.I.S\Jarvis Using Python\DataBase\chrome user data"
edge_usr_data = r"p:\Python\J.A.R.V.I.S\Jarvis Using Python\DataBase\edge user data"

def usr_data(usr_data):
    return os.path.exists(usr_data)

# Bing Cookies Extractor
def bing_cookies():
    '''
    Extract cookies from "bing.com" and return them as a dictionary.
    This is a helper function to make it easier to use it as a unit test
    '''
    # Set up Browser options
    edge_options = EdgeOptions()

    # Edge Arguments
    edge_options.add_experimental_option('excludeSwitches', ['enable-logging'])
    edge_options.add_argument("--disable-blink-features=AutomationControlled")
    edge_options.add_argument("--disable-infobars")
    edge_options.add_argument("--start-maximized")
    edge_options.add_argument("--no-sandbox")
    edge_options.add_argument("--disable-extensions")
    edge_options.add_argument("--disable-dev-shm-usage")
    edge_options.add_argument("--log-level=3")  # Disable logging
    edge_options.add_argument("--silent")  # Disable console output
    edge_options.add_argument("--headless")
    edge_options.add_argument(f"--user-data-dir={edge_usr_data}")

    # Set up Selenium WebDriver with Edge options
    edge_driver = webdriver.Edge(options=edge_options)

    edge_driver.get("https://login.live.com/")
    sleep(10)
    # Navigate to bing.com
    edge_driver.get("https://bing.com")

    # Extract cookies
    cookies = edge_driver.get_cookies()

    # Update the "Api.json" file with the new value of messages_left
    with open("Data/Api.json", "r") as file:
        api_data = json.load(file)
    
    api_data["Bing_Cookies"][0]["Cookies"] = cookies

    with open("Data/Api.json", "w") as file:
        json.dump(api_data, file, indent=4)
    
    edge_driver.quit()

# Chrome Cookies Extractor
def chrome_cookies(email, password):
    '''
    Set up Chrome cookies to connect to Google. This is a wrapper around Selenium's Chrome module.
     
    @param email - Email address of the user to be contacted
    @param password - Password of the user to be
    '''
    # Disable logging messages
    logging.disable(logging.INFO)

    # Set up Browser options
    chrome_options = ChromeOptions()

    # Chrome Arguments
    chrome_options.add_experimental_option('excludeSwitches', ['enable-logging'])
    chrome_options.add_argument("--disable-blink-features=AutomationControlled")
    chrome_options.add_argument("--disable-infobars")
    chrome_options.add_argument("--start-maximized")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-extensions")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("--log-level=3")  # Disable logging
    chrome_options.add_argument("--silent")  # Disable console output
    chrome_options.add_argument(f"--user-data-dir={chrm_usr_data}")

    if usr_data(chrm_usr_data):
        chrome_options.add_argument("--headless")

    # Set up Selenium WebDriver with Chrome options
    chrm_driver = webdriver.Chrome(options=chrome_options)

    # Google bard Cookie Extractor
    def bard_cookie():
        # Navigate to bard.google.com
        chrm_driver.get("https://bard.google.com")

        # Extract cookies
        cookies = chrm_driver.get_cookies()

        # Update the "Api.json" file with the new value of messages_left
        with open("Data/Api.json", "r") as file:
            api_data = json.load(file)
        
        api_data["Chrome_Cookies"][0]["Cookies"] = cookies

        with open("Data/Api.json", "w") as file:
            json.dump(api_data, file, indent=4)

    # Chrome login
    if usr_data(chrm_usr_data) == False:
        chrm_driver.get(r"https://accounts.google.com")

        # Find and fill in the email field
        email_field = chrm_driver.find_element(By.ID, "identifierId")
        email_field.send_keys(email)

        # Click the "Next" button
        next_button = chrm_driver.find_element(By.ID, "identifierNext")
        next_button.click()

        # Wait for the password field to appear
        sleep(8)  # Adjust the sleep duration if needed

        # Find and fill in the password field using XPath
        password_field = chrm_driver.find_element(By.XPATH, '/html/body/div[1]/div[1]/div[2]/div/c-wiz/div/div[2]/div/div[1]/div/form/span/section[2]/div/div/div[1]/div[1]/div/div/div/div/div[1]/div/div[1]/input')
        password_field.send_keys(password)

        # Click the "Next" button
        next_button = chrm_driver.find_element(By.ID, "passwordNext")
        next_button.click()

        sleep(3)
        bard_cookie()

    else:
        sleep(2)
        bard_cookie()

    # Close the browser
    chrm_driver.quit()

def api_updater():
    '''
    Updates the API by running the chrome_cookies function. It is called every 5 seconds

    @return A dictionary containing the following keys: chrome_id - The ID of the Chrome user who is requesting the update
    '''
    with open("Data/Api.json", "r") as f:
        ids = json.load(f)

    chrome_id = ids["Chrome_ID"][0]
    email = chrome_id["email"]
    password = chrome_id["password"]

    # Run the chrome_cookies function with the given email and password
    chrome_cookies(email, password)
    bing_cookies()

    # Read the cookies from the JSON file
    with open('Data/Api.json', 'r') as file:
        cookies = json.load(file)
        cookies = cookies['Chrome_Cookies'][0]['Cookies']

    def extract_cookie_value(cookie_name, cookies_list):
        '''
        Extract value of a cookie. This function is used to extract the value of a cookie given its name.
        
        @param cookie_name - The name of the cookie we are looking for.
        @param cookies_list - The list of cookies that will be searched.
        
        @return The value of the cookie or None if not found
        '''
        for cookie in cookies_list:
            if cookie['name'] == cookie_name:
                return cookie['value']
        return None

    # Extract the value from the '__Secure-1PSID' cookie
    cookie_name = '__Secure-1PSID'
    cookie_value = extract_cookie_value(cookie_name, cookies)

    # Read the JSON file containing the values
    with open('Data/Api.json', 'r') as file:
        data = json.load(file)

    # Update the 'Bard_Token' value with the cookie value
    if 'Bard' in data:
        bard_data = data['Bard'][0]
        if 'Bard_Token' in bard_data:
            bard_data['Bard_Token'] = cookie_value

    # Write the updated data back to the JSON file
    with open('Data/Api.json', 'w') as file:
        json.dump(data, file, indent=4)

def save_datetime_to_json(datetime_obj):
    '''
    Saves the datetime object to the json file. This is used to keep track of messages_left
     
    @param datetime_obj - datetime object to save
    '''
    data = {"last_updated": datetime_obj.isoformat()}
    # Update the "Api.json" file with the new value of messages_left
    with open("Data/Api.json", "r") as file:
        api_data = json.load(file)
    
    api_data["Date_Time"][0]["last_updated"] = data["last_updated"]

    with open("Data/Api.json", "w") as file:
        json.dump(api_data, file, indent=4)

def load_datetime_from_json():
    '''
    Load last_updated from json file.
    This is used to check if we are running on Galaxy and if so return the datetime.

    @return datetime or None if not
    '''
    if os.path.exists("Data/Api.json"):
        with open("Data/Api.json", "r") as file:
            data = json.load(file)
            last_updated = data["Date_Time"][0]["last_updated"]
            if last_updated:
                return datetime.datetime.fromisoformat(last_updated)
    return None

def extracted():
    '''
    Checks if Bard API has been updated since 72 hours ago. If so, calls api_updater
    '''
    last_updated = load_datetime_from_json()
    current_datetime = datetime.datetime.now()

    if last_updated is None or (current_datetime - last_updated).total_seconds() >= 72 * 60 * 60:
        print("Updating Bard API & Bing Cookies")
        api_updater()
        save_datetime_to_json(current_datetime)
        print("Bard API & Bing Cookies Updated Successfully")

extracted()
# bing_cookies()
```

**Comment by phamxtien** [comment]
Fix it with

```
def getCookies(url):
    import browser_cookie3
    browsers = [
        # browser_cookie3.chrome,
        # browser_cookie3.chromium,
        # browser_cookie3.opera,
        # browser_cookie3.opera_gx,
        # browser_cookie3.brave,
        browser_cookie3.edge,
        # browser_cookie3.vivaldi,
        # browser_cookie3.firefox,
        # browser_cookie3.librewolf,
        # browser_cookie3.safari,
    ]
    for browser_fn in browsers:
        # if browser isn't installed browser_cookie3 raises exception
        # hence we need to ignore it and try to find the right one
        try:
            cookies = []
            cj = browser_fn(domain_name=url)
            for cookie in cj:
                cookies.append(cookie.__dict__)
            return cookies
        except:
            continue
```
and 
```
bot = EdgeGPT.Chatbot(cookies=getCookies('.bing.com'))
```

**Comment by Meshwa428** [comment]
thanks

**Comment by Meshwa428** [comment]
is acheong still fixing this issue or he isn't

**Comment by leez7one** [comment]
> Thanks for the help, but we windows users have to do that stuff manualy or in WSL, i think automating it with selenium might be a good idea, I mean we can use selenium to automate edge browser. Just log in to it, send a hi to bing and done. I am starting to work on it, after i complete i will provide the code snippet here

Any updates ?

**Comment by cousintiz** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues and checked the recent builds/commits
> 
> ### What happened?
> After using it 30 times, it prompts this, what should I do?
> 
> ### Steps to reproduce the problem
> 1. After using it 30 times, it prompts this, what should I do?
> 
> ### What should have happened?
> After using it 30 times, it prompts this, what should I do?
> 
> ### Version where the problem happens
> 3.9
> 
> ### What Python version are you running this with?
> 3.9
> 
> ### What is your operating system ?
> Linux
> 
> ### Command Line Arguments
> ```shell
> no
> ```
> 
> ### Console logs
> ```shell
> Traceback (most recent call last):
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/www/wwwroot/ceshi701/EdgeGPT/bbb.py", line 31, in chat
>     responses = loop.run_until_complete(get_responses())
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/www/wwwroot/ceshi701/EdgeGPT/bbb.py", line 18, in get_responses
>     async for final, response in bot.ask_stream(prompt=question, conversation_style=ConversationStyle.creative):
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/EdgeGPT/EdgeGPT.py", line 185, in ask_stream
>     async for response in self.chat_hub.ask_stream(
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/EdgeGPT/chathub.py", line 197, in ask_stream
>     raise Exception(
> Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
> [2023-07-02 01:31:19,185] ERROR in app: Exception on /chat [POST]
> Traceback (most recent call last):
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/www/wwwroot/ceshi701/EdgeGPT/bbb.py", line 31, in chat
>     responses = loop.run_until_complete(get_responses())
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/www/wwwroot/ceshi701/EdgeGPT/bbb.py", line 18, in get_responses
>     async for final, response in bot.ask_stream(prompt=question, conversation_style=ConversationStyle.creative):
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/EdgeGPT/EdgeGPT.py", line 185, in ask_stream
>     async for response in self.chat_hub.ask_stream(
>   File "/www/wwwroot/ceshi701/EdgeGPT/7815696ecbf1c96e6894b779456d330e_venv/lib/python3.9/site-packages/EdgeGPT/chathub.py", line 197, in ask_stream
>     raise Exception(
> Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
> ```
> 
> ### Additional information
> ok

having the same problem

**Comment by Meshwa428** [comment]
> > Thanks for the help, but we windows users have to do that stuff manualy or in WSL, i think automating it with selenium might be a good idea, I mean we can use selenium to automate edge browser. Just log in to it, send a hi to bing and done. I am starting to work on it, after i complete i will provide the code snippet here
> 
> Any updates ?

Trying it. still figuring out that how does their captcha works

**Comment by Meshwa428** [comment]
![SC](https://github.com/acheong08/EdgeGPT/assets/135232056/542d4418-8347-48e1-87ad-6946a72989fc)
Guys, I found out that bing shows this captcha when it asks user to solve it. Any clues on how to solve it using python, Anyone??

**Comment by Dima-369** [comment]
> Guys, I found out that bing shows this captcha when it asks user to solve it. Any clues on how to solve it using python, Anyone??

Hah, I just tried it with Google Bard (see https://github.com/dsdanielpark/Bard-API), but it doesn't get them right 😄  

![image](https://github.com/acheong08/EdgeGPT/assets/15002298/4745c123-61b9-4172-879e-29c5b5c99235)

**Comment by Meshwa428** [comment]
It isn't that great, but it seems pretty accurate. Bard is great at images
i think. Thanks for the solution👍

**Comment by ahmed0x77** [comment]
i got the same problem "solve CAPTCHA to continue"

**Comment by peteh** [comment]
Same for me. I can also not easily solve it by logging in with the browser

**Comment by OmarHedeya95** [comment]
> Fix it with
> 
> ```
> def getCookies(url):
>     import browser_cookie3
>     browsers = [
>         # browser_cookie3.chrome,
>         # browser_cookie3.chromium,
>         # browser_cookie3.opera,
>         # browser_cookie3.opera_gx,
>         # browser_cookie3.brave,
>         browser_cookie3.edge,
>         # browser_cookie3.vivaldi,
>         # browser_cookie3.firefox,
>         # browser_cookie3.librewolf,
>         # browser_cookie3.safari,
>     ]
>     for browser_fn in browsers:
>         # if browser isn't installed browser_cookie3 raises exception
>         # hence we need to ignore it and try to find the right one
>         try:
>             cookies = []
>             cj = browser_fn(domain_name=url)
>             for cookie in cj:
>                 cookies.append(cookie.__dict__)
>             return cookies
>         except:
>             continue
> ```
> 
> and
> 
> ```
> bot = EdgeGPT.Chatbot(cookies=getCookies('.bing.com'))
> ```

This works! Thanks a lot! Sometimes you need to open Bing and have one chat but then works perfectly

**Comment by Meshwa428** [comment]
Guys i found this captcha element, if some one can fix it with this, i think we can get a basic idea of what the captcha is

<iframe src="https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/6t8cg/0x4AAAAAAADptsa1Vbw0CGbV/light/normal" allow="cross-origin-isolated; fullscreen" sandbox="allow-same-origin allow-scripts allow-popups" id="cf-chl-widget-6t8cg" tabindex="0" title="Widget containing a Cloudflare security challenge" style="border: none; overflow: hidden; width: 300px; height: 65px;"></iframe>
