### ISSUE TITLE
Traceback (most recent call last):   File "/home/user/.local/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events     client_awake = await self.gather_event_data(event)   File "/home/user/.local/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data     data, client_awake = await self.get_message(event, timeout=receive_timeout)   File "/home/user/.local/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message     return PredictBody(**data), True   File "/home/user/.local/lib/python3.10/site-packages/pydantic/main.py", line 150, in __init__     __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__) pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody event_id   Field required [type=missing, input_value={'fn_index': 1, 'data': [...on_hash': 'ss70oxjj9qc'}, input_type=dict]     For further information visit https://errors.pydantic.dev/2.1.2/v/missing

### ISSUE THREAD

**Issue by xiaolvtongxue-zt** [acheong08/EdgeGPT#602]
使用最新的版本，运行是一直在等待，刷新页面后，看到的报错信息

**Comment by Bytxy** [comment]
me too
