### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by marhmm** [acheong08/EdgeGPT#96]
Hello,

I am using EdgeGPT v0.0.51 with command:
`python3 -m EdgeGPT --cookie-file "/home/xxx/cookies.json" ` 

It is working fine but after waiting a few minutes I always (?) get the following error when trying to send an additional request:

```
Bot:
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 968, in transfer_data
    message = await self.read_message()
  File "/home/xxx/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1038, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/xxx/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/xxx/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1170, in read_frame
    frame = await Frame.read(
  File "/home/xxx/.local/lib/python3.10/site-packages/websockets/legacy/framing.py", line 69, in read
    data = await reader(2)
  File "/usr/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 916, in write
    n = self._sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xxx/.local/lib/python3.10/site-packages/EdgeGPT.py", line 356, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/xxx/.local/lib/python3.10/site-packages/EdgeGPT.py", line 322, in main
    async for final, response in bot.ask_stream(prompt=prompt):
  File "/home/xxx/.local/lib/python3.10/site-packages/EdgeGPT.py", line 250, in ask_stream
    async for response in self.chat_hub.ask_stream(prompt=prompt):
  File "/home/xxx/.local/lib/python3.10/site-packages/EdgeGPT.py", line 202, in ask_stream
    objects = str(await self.wss.recv()).split(DELIMITER)
  File "/home/xxx/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/home/xxx/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```

**Comment by PRO-2684** [comment]
It seems that Bing closes the connection 'cause you haven't interacted for a while.

**Comment by acheong08** [comment]
Should be fixed in latest version

**Comment by LZC6244** [comment]
Version 0.3.6 also has this problem
